In [5]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## Import database

In [3]:
pd.set_option('display.max_columns', None)
df = pd.read_parquet('taxi_trip_engineering.parquet')
df

,Date,user_id,Time,Booking ID,Booking Status,Driver Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon,completed_at
0,2026-01-01,RIDE-000001,00:19:34,CNR4352144,Completed,Online,CID8362794,Motorcycle,Pasar Baru,Cilandak Timur,10.8,38.9,99000.0,37.98,4.8,4.8,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation,2026-01-01 00:00:00,0,0,110,18,4,4.312727,3.663049,1442.4804,6.162792,0,0,1,0.000000,1.000000,0.0,1.0,1,29.026393,0.00,4.625,0,0,4.8,1373,5,228.833333,5,11.502885,3.686376,1.791759,12.700787,3.394508,37.98,5,0,30.820000,31.20,9.496684,9.620000,10.80,29.024763,8.400510,1373,28.940847,8.432545,3,30.060481,8.487883,7.010743,9.6,23.04,4.8,4.8,4,29.983461,8.483689,110_18_0,38.9,10.8,19,110_0_19,18_0_19,18.90,11.55,2599.789916,0,29.126926,8.283577,-6.164901,106.833467,-6.289466,106.812477,2026-01-01 00:11:33
1,2026-01-01,RIDE-000002,01:35:18,CNR9147645,Completed,Online,CID8300238,Car,Kali Anyar,Rawamangun,8.5,15.1,114000.0,39.29,4.2,4.1,Uber Wallet,No Cancellation,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,No Reason Provided,2026-01-01 00:01:00,1,0,47,147,3,4.312727,3.696103,1543.7041,6.268174,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,0.10,4.150,0,1,4.2,1360,2,453.333333,2,11.643962,2.778819,1.098612,12.700787,3.394508,39.29,2,0,18.300000,18.30,4.525483,7.000000,7.00,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.105852,8.3,17.22,4.1,4.2,3,28.674842,8.418815,47_147_1,15.1,8.5,35,47_1_35,147_1_35,27.00,3.40,2894.135567,1,29.069894,8.250120,-7.550534,110.819452,-6.195928,106.884725,2026-01-01 00:04:24
2,2026-01-01,RIDE-000003,01:37:50,CNR1009222,Cancelled by Driver,Online,CID2030746,Go Sedan,Serdang,Pengadegan,7.4,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Traffic Issue,0.0,App Error,2026-01-01 00:02:00,1,0,147,125,1,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,4.3,1360,4,272.000000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,28.750000,28.80,0.100000,10.900000,9.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,147_125_1,28.8,7.4,37,147_1_37,125_1_37,20.10,8.60,17380.352645,2,28.865348,8.671032,3.034065,101.705568,-6.248914,106.854349,2026-01-01 00:10:36
3,2026-01-01,RIDE-000004,01:48:03,CNR2740479,Cancelled by Driver,Online,CID3231181,Auto,Tanah Tinggi,Kampung Rawa,5.6,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,Personal Issue,0.0,No Reason Provided,2026-01-01 00:03:00,1,0,160,61,2,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,4.3,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.914286,25.90,3.223057,6.571429,5.60,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,160_61_1,28.8,5.6,48,160_1_48,61_1_48,28.40,5.80,17380.352645,2,28.865348,8.671032,57.506636,-5.003837,-6.179512,106.855659,2026-01-01 00:08:48
4,2026-01-01,RIDE-000005,01:49:56,CNR7650148,Cancelled by Driver,Online,CID3381661,Go Sedan,Jati,Batu Ceper,6.2,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Wrong Pickup Location,Cancelled,Wrong Location,1.0,Route Problem,2026-01-01 00:04:00,1,0,40,2,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,0.0,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,23.542857,20.60,6.484303,5.514286,6.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,40_2_1,28.8,6.2,49,40_1_49,2_1_49,31.57,6.60,17380.352645,2,28.865348,8.671032,-7.689434,-39.006074,-6.172027,106.665287,2026-01-01 00:10:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2026-04-15,RIDE-149996,22:58:00,CNR9030698,Completed,Online,CID6939658,Motorcycle,Setu,Kembangan Utara,6.9,35.8,440000.0,12.85,4.4,4.8,UPI,Cancelled,Booked by Mistake,Cancelled,Wrong Location,0.0,App Error,2026-04-15 03:55:00,22,0,148,84,2,0.558696,2.628285,165.1225,3.584690,0,0,1,-0.500000,0.866025,0.0,1.0,1,25.260000,-0.40,4.600,0,0,0.0,5441,6,777.285714,6,12.994532,3.605498,1.945910,12.742693,3.268047,12.85,6,0,27.016667,26.15,6.237120,8.683333,7.95,29.112571,8.432659,5441,28.940847,8.432545,1,28.152500,8.043096,4.260973,9.2,21.12,4.4,4.8,4,29.983461,8.483689,148_84_22,35.8,6.9,58,148_22_58,84_22_58,28.80,7.55,33976.833977,3,29.283535,8.333253,-6.341971,106.664700,-6.173267,106.742726,2026-04-15 04:02:33
149996,2026-04-15,RIDE-149997,23:03:14,CNR1507833,Completed,Online,CID9905090,eBike,Jatinegara,Grogol Selatan,7.9,33.6,279000.0,39.36,3.8,4.3,UPI,No Cancellation,Changed Mind,No Cancellation,Vehicle Breakdown,0.0,No Reason Provided,2026-04-15 03:56:00,23,0,41,43,0,1.640000,3.697839,1549.2096,6.273755,0,0,1,-0.258819,0.965926,0.0,1.0,1,25.633333,-0.50,4.050,1,0,3.8,2762,4,552.400000,4,12.538971,3.543854,1.609438,12.331425,3.282164,39.36,4,0,27.625000,27.30,10.463389,7.750000,8.60,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,7.110858,8.1,16.34,3.8,4.3,3,28.674842,8.418815,41_43_23,33.6,7.9,3,41_23_3,43_23_3,15.20,6.30,7070.451090,1,29.069894,8.250120,-6.214925,106.870339,-6.230900,106.780309,2026-04-15 04:02:18
149997,2026-04-15,RIDE-149998,23:17:05,CNR2265113,Completed,Online,CID4170406,Car,Kebon Melati,Galur,9.9,39.9,1855.0,38.91,4.3,4.6,UPI,Cancelled,Changed Mind,Cancelled,Vehicle Breakdown,1.0,Ride Cancelled Midway,2026-04-15 03:57:00,23,0,69,36,4,1.621250,3.686627,1513.9881,6.237788,0,0,1,-0.258819,0.965926,0.0,1.0,1,27.000000,-0.30,4.450,0,0,0.0,2762,5,460.333333,5,7.526179,3.711130,1.791759,13.003582,3.332205,38.91,5,0,29.580000,28.80,8.277802,8.020000,9.90,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,7.078542,8.9,19.78,4.3,4.6,3,28.674842,8.418815,69_36_23,39.9,9.9,17,69_23_17,36_23_17,41.10,4.70,47.551910,0,29.126926,8.283577,-6.197487,106.816546,-7.950719,110.202904,2026-04-15 04:01:42
149998,2026-04-15,RIDE-149999,23:21:12,CNR4066733,Completed,Online,CID8938559,Uber XL,Utan Panjang,Pinang Ranti,2.6,26.7,520000.0,36.37,5.0,4.3,Uber Wallet,Cancelled,Changed Mind,Cancelled,Wrong Location,0.0,Route Problem,2026-04-15 03:58:00,23,0,174,132,1,1.515417,3.620868,1322.7769,6.030755,0,0,1,-0.258819,0.965926,0.0,1.0,1,25.833333,0.45,4.625,0,0,0.0,2762,4,552.400000,4,13.161586,3.321432,1.609438,12.861867,3.289645,36.37,4,0,26.050000,26.30,2.487971,6.675000,6.65,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,6.889998,9.3,21.50,4.3,5.0,4,29.983461,8.483689,174_132_23,26.7,2.6,21,174_23_21,132_23_21,27.30,9.20,14258.294489,3,29.283535,8.333253,-6.164872,106.854815,-6.288428,106.883331,2026-04-15 04:07:12
149999,2026-04-15,RIDE-150000,23:36:11,CNR6915581,Incomplete,Offline,CID5185745,Auto,Mampang Prapatan,Tegal Parang,3.5,11.9,571000.0,2.67,4.3,4.5,UPI,Cancelled,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,Route Problem,2026-04-15 03:59:00,23,0,94,168,1,0.111250,1.300192,7.1289,1.634013,0,0,1,-0.258819,0.965926,0.0,1.0,1,29.666667,-0.20,4.400,0,0,4.3,2762,10,251.090909,10,13.255146,2.557227,2.397895,12.865608,3.423176,2.67,10,0,27.890000,28.80,6.833813,8.140000,8.35,28.868356,8.447502,2762,28.940847,8.432545,0,27.916399,7.952362,1.482556,8.8,19.35,4.3,4.5,3,28.674842,8.418815,94_168_23,11.9,3.5,36,94_23_36,168_23_36,31.05,17.10,206137.184116,3,29.283535,8.333253,-6.250894,106.823022,-6.248909,106.829606,2026-04-15 04:16:06

In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)
df = pd.read_parquet('taxi_trip_engineering_2.parquet')
df

,Date,user_id,Time,Booking ID,Booking Status,Driver Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon,completed_at,estimated_fare
0,2026-01-01,RIDE-000001,00:19:34,CNR4352144,Completed,Online,CID8362794,Motorcycle,Pasar Baru,Cilandak Timur,10.8,38.9,99000.0,37.98,4.8,4.8,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation,2026-01-01 00:00:00,0,0,110,18,4,4.312727,3.663049,1442.4804,6.162792,0,0,1,0.000000,1.000000,0.0,1.0,1,29.026393,0.00,4.625,0,0,4.8,1373,5,228.833333,5,11.502885,3.686376,1.791759,12.700787,3.394508,37.98,5,0,30.820000,31.20,9.496684,9.620000,10.80,29.024763,8.400510,1373,28.940847,8.432545,3,30.060481,8.487883,7.010743,9.6,23.04,4.8,4.8,4,29.983461,8.483689,110_18_0,38.9,10.8,19,110_0_19,18_0_19,18.90,11.55,2599.789916,0,29.126926,8.283577,-6.164901,106.833467,-6.289466,106.812477,2026-01-01 00:11:33,38698.65
1,2026-01-01,RIDE-000002,01:35:18,CNR9147645,Completed,Online,CID8300238,Car,Kali Anyar,Rawamangun,8.5,15.1,114000.0,39.29,4.2,4.1,Uber Wallet,No Cancellation,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,No Reason Provided,2026-01-01 00:01:00,1,0,47,147,3,4.312727,3.696103,1543.7041,6.268174,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,0.10,4.150,0,1,4.2,1360,2,453.333333,2,11.643962,2.778819,1.098612,12.700787,3.394508,39.29,2,0,18.300000,18.30,4.525483,7.000000,7.00,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.105852,8.3,17.22,4.1,4.2,3,28.674842,8.418815,47_147_1,15.1,8.5,35,47_1_35,147_1_35,27.00,3.40,2894.135567,1,29.069894,8.250120,-7.550534,110.819452,-6.195928,106.884725,2026-01-01 00:04:24,188314.36
2,2026-01-01,RIDE-000003,01:37:50,CNR1009222,Cancelled by Driver,Online,CID2030746,Go Sedan,Serdang,Pengadegan,7.4,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Traffic Issue,0.0,App Error,2026-01-01 00:02:00,1,0,147,125,1,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,4.3,1360,4,272.000000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,28.750000,28.80,0.100000,10.900000,9.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,147_125_1,28.8,7.4,37,147_1_37,125_1_37,20.10,8.60,17380.352645,2,28.865348,8.671032,3.034065,101.705568,-6.248914,106.854349,2026-01-01 00:10:36,413999.88
3,2026-01-01,RIDE-000004,01:48:03,CNR2740479,Cancelled by Driver,Online,CID3231181,Auto,Tanah Tinggi,Kampung Rawa,5.6,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,Personal Issue,0.0,No Reason Provided,2026-01-01 00:03:00,1,0,160,61,2,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,4.3,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.914286,25.90,3.223057,6.571429,5.60,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,160_61_1,28.8,5.6,48,160_1_48,61_1_48,28.40,5.80,17380.352645,2,28.865348,8.671032,57.506636,-5.003837,-6.179512,106.855659,2026-01-01 00:08:48,413999.46
4,2026-01-01,RIDE-000005,01:49:56,CNR7650148,Cancelled by Driver,Online,CID3381661,Go Sedan,Jati,Batu Ceper,6.2,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Wrong Pickup Location,Cancelled,Wrong Location,1.0,Route Problem,2026-01-01 00:04:00,1,0,40,2,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,0.0,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,23.542857,20.60,6.484303,5.514286,6.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,40_2_1,28.8,6.2,49,40_1_49,2_1_49,31.57,6.60,17380.352645,2,28.865348,8.671032,-7.689434,-39.006074,-6.172027,106.665287,2026-01-01 00:10:36,413958.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2026-04-15,RIDE-149996,22:58:00,CNR9030698,Completed,Online,CID6939658,Motorcycle,Setu,Kembangan Utara,6.9,35.8,440000.0,12.85,4.4,4.8,UPI,Cancelled,Booked by Mistake,Cancelled,Wrong Location,0.0,App Error,2026-04-15 03:55:00,22,0,148,84,2,0.558696,2.628285,165.1225,3.584690,0,0,1,-0.500000,0.866025,0.0,1.0,1,25.260000,-0.40,4.600,0,0,0.0,5441,6,777.285714,6,12.994532,3.605498,1.945910,12.742693,3.268047,12.85,6,0,27.016667,26.15,6.237120,8.683333,7.95,29.112571,8.432659,5441,28.940847,8.432545,1,28.152500,8.043096,4.260973,9.2,21.12,4.4,4.8,4,29.983461,8.483689,148_84_22,35.8,6.9,58,148_22_58,84_22_58,28.80,7.55,33976.833977,3,29.283535,8.333253,-6.341971,106.664700,-6.173267,106.742726,2026-04-15 04:02:33,526648.19
149996,2026-04-15,RIDE-149997,23:03:14,CNR1507833,Completed,Online,CID9905090,eBike,Jatinegara,Grogol Selatan,7.9,33.6,279000.0,39.36,3.8,4.3,UPI,No Cancellation,Changed Mind,No Cancellation,Vehicle Breakdown,0.0,No Reason Provided,2026-04-15 03:56:00,23,0,41,43,0,1.640000,3.697839,1549.2096,6.273755,0,0,1,-0.258819,0.965926,0.0,1.0,1,25.633333,-0.50,4.050,1,0,3.8,2762,4,552.400000,4,12.538971,3.543854,1.609438,12.331425,3.282164,39.36,4,0,27.625000,27.30,10.463389,7.750000,8.60,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,7.110858,8.1,16.34,3.8,4.3,3,28.674842,8.418815,41_43_23,33.6,7.9,3,41_23_3,43_23_3,15.20,6.30,7070.451090,1,29.069894,8.250120,-6.214925,106.870339,-6.230900,106.780309,2026-04-15 04:02:18,214622.14
149997,2026-04-15,RIDE-149998,23:17:05,CNR2265113,Completed,Online,CID4170406,Car,Kebon Melati,Galur,9.9,39.9,1855.0,38.91,4.3,4.6,UPI,Cancelled,Changed Mind,Cancelled,Vehicle Breakdown,1.0,Ride Cancelled Midway,2026-04-15 03:57:00,23,0,69,36,4,1.621250,3.686627,1513.9881,6.237788,0,0,1,-0.258819,0.965926,0.0,1.0,1,27.000000,-0.30,4.450,0,0,0.0,2762,5,460.333333,5,7.526179,3.711130,1.791759,13.003582,3.332205,38.91,5,0,29.580000,28.80,8.277802,8.020000,9.90,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,7.078542,8.9,19.78,4.3,4.6,3,28.674842,8.418815,69_36_23,39.9,9.9,17,69_23_17,36_23_17,41.10,4.70,47.551910,0,29.126926,8.283577,-6.197487,106.816546,-7.950719,110.202904,2026-04-15 04:01:42,25411.58
149998,2026-04-15,RIDE-149999,23:21:12,CNR4066733,Completed,Online,CID8938559,Uber XL,Utan Panjang,Pinang Ranti,2.6,26.7,520000.0,36.37,5.0,4.3,Uber Wallet,Cancelled,Changed Mind,Cancelled,Wrong Location,0.0,Route Problem,2026-04-15 03:58:00,23,0,174,132,1,1.515417,3.620868,1322.7769,6.030755,0,0,1,-0.258819,0.965926,0.0,1.0,1,25.833333,0.45,4.625,0,0,0.0,2762,4,552.400000,4,13.161586,3.321432,1.609438,12.861867,3.289645,36.37,4,0,26.050000,26.30,2.487971,6.675000,6.65,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,6.889998,9.3,21.50,4.3,5.0,4,29.983461,8.483689,174_132_23,26.7,2.6,21,174_23_21,132_23_21,27.30,9.20,14258.294489,3,29.283535,8.333253,-6.164872,106.854815,-6.288428,106.883331,2026-04-15 04:07:12,543578.57
149999,2026-04-15,RIDE-150000,23:36:11,CNR6915581,Incomplete,Offline,CID5185745,Auto,Mampang Prapatan,Tegal Parang,3.5,11.9,571000.0,2.67,4.3,4.5,UPI,Cancelled,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,Route Problem,2026-04-15 03:59:00,23,0,94,168,1,0.111250,1.300192,7.1289,1.634013,0,0,1,-0.258819,0.965926,0.0,1.0,1,29.666667,-0.20,4.400,0,0,4.3,2762,10,251.090909,10,13.255146,2.557227,2.397895,12.865608,3.423176,2.67,10,0,27.890000,28.80,6.833813,8.140000,8.35,28.868356,8.447502,2762,28.940847,8.432545,0,27.916399,7.952362,1.482556,8.8,19.35,4.3,4.5,3,28.674842,8.418815,94_168_23,11.9,3.5,36,94_23_36,168_23_36,31.05,17.10,206137.184116,3,29.283535,8.333253,-6.250894,106.823022,-6.248909,106.829606,2026-04-15 04:16:06,543618.40

In [6]:
filtered_df = df[(df['Drop Location'] == 'Ciganjur') & (df['Pickup Location'] == 'Mangga Besar')]
filtered_df

,Date,user_id,Time,Booking ID,Booking Status,Driver Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon,completed_at,estimated_fare
4671,2026-01-04,RIDE-004672,12:42:14,CNR2276359,Completed,Online,CID7936724,Auto,Mangga Besar,Ciganjur,3.9,39.2,433000.0,9.70,4.6,4.7,UPI,Cancelled,Booked by Mistake,Cancelled,Traffic Issue,1.0,Route Problem,2026-01-04 05:51:00,12,4,95,13,4,0.746154,2.370244,94.0900,3.114482,0,0,0,1.224647e-16,-1.000000,-0.433884,-0.900969,2,29.026393,-0.10,4.625,0,0,0.0,7006,12,538.923077,12,12.978495,3.693867,2.564949,12.700787,3.394508,19.40,24,0,28.491667,28.8,6.73248,10.491667,13.05,29.176749,8.463389,7006,29.077287,8.478628,0,27.916399,7.952362,3.649131,9.3,21.62,4.6,4.7,4,29.983461,8.483689,95_13_12,33.433333,9.733333,42,95_12_42,13_12_42,44.30,4.30,44183.673469,3,29.283535,8.333253,-6.149804,106.826983,-6.335585,106.807062,2026-01-04 05:55:18.000,516454.17
14992,2026-01-11,RIDE-014993,00:14:11,CNR4776058,Completed,Online,CID4915901,Auto,Mangga Besar,Ciganjur,2.3,25.3,158000.0,7.94,4.3,4.9,UPI,Cancelled,Found Alternative,No Cancellation,No Reason Provided,0.0,Customer Issue,2026-01-11 09:52:00,0,1,95,13,4,4.312727,2.190536,63.0436,2.817801,0,0,1,0.000000e+00,1.000000,0.781831,0.623490,1,39.200000,-0.60,4.600,0,0,4.3,1373,12,105.615385,12,11.970357,3.269569,2.564949,12.978495,3.693867,7.94,12,0,28.491667,28.8,6.73248,10.491667,13.05,29.024763,8.400510,1373,28.998560,8.431050,0,27.916399,7.952362,3.242093,9.2,21.07,4.3,4.9,4,29.983461,8.483689,95_13_0,25.300000,2.300000,14,95_0_14,13_0_14,28.80,6.50,19651.741294,1,29.069894,8.250120,-6.149804,106.826983,-6.335585,106.807062,2026-01-11 09:58:30.000,199149.57
16255,2026-01-12,RIDE-016256,23:57:49,CNR6155968,Cancelled by Driver,Online,CID9174743,eBike,Mangga Besar,Ciganjur,3.5,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Personal Issue,0.0,Customer Issue,2026-01-12 06:55:00,23,3,95,13,4,0.988333,3.207613,562.6384,4.870318,0,0,1,-2.588190e-01,0.965926,0.433884,-0.900969,1,32.250000,-0.20,4.400,0,0,4.3,2762,12,212.461538,12,12.933624,3.394508,2.564949,12.596427,3.504055,23.72,12,0,28.491667,28.8,6.73248,10.491667,13.05,28.868356,8.447502,2762,29.027004,8.437700,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,95_13_23,28.800000,3.500000,57,95_23_57,13_23_57,24.97,9.33,17380.352645,2,28.865348,8.671032,-6.149804,106.826983,-6.335585,106.807062,2026-01-12 07:04:19.800,413780.96
16398,2026-01-12,RIDE-016399,12:05:54,CNR5176593,Completed,Online,CID7619160,Motorcycle,Mangga Besar,Ciganjur,12.5,25.3,554000.0,28.34,4.3,4.4,Cash,Cancelled,No Reason Provided,No Cancellation,No Reason Provided,0.0,No Reason Provided,2026-01-12 09:18:00,12,4,95,13,4,2.180000,3.378952,803.1556,5.323533,0,0,0,1.224647e-16,-1.000000,-0.433884,-0.900969,2,31.100000,-0.10,4.350,0,0,4.3,7006,12,538.923077,12,13.224922,3.269569,2.564949,12.721889,3.468856,56.68,24,0,28.491667,28.8,6.73248,10.491667,13.05,29.176749,8.463389,7006,29.077287,8.478628,2,29.119842,8.707975,6.211164,8.7,18.92,4.3,4.4,3,28.674842,8.418815,95_13_12,33.433333,9.733333,5,95_12_5,13_12_5,17.70,6.80,19479.606188,3,29.283535,8.333253,-6.149804,106.826983,-6.335585,106.807062,2026-01-12 09:24:48.000,537672.11
25140,2026-01-18,RIDE-025141,20:50:11,CNR4229038,Completed,Online,CID8954138,Car,Mangga Besar,Ciganjur,14.1,33.3,573000.0,7.81,4.7,4.4,Debit Card,No Cancellation,Driver Taking Too Long,No Cancellation,Personal Issue,1.0,Customer Issue,2026-01-18 11:00:00,20,4,95,13,4,0.371905,2.175887,60.9961,2.794638,1,0,0,-8.660254e-01,0.500000,-0.433884,-0.900969,3,29.650000,0.30,4.550,0,0,4.7,9630,12,740.769231,12,13.258643,3.535145,2.564949,12.873263,3.422633,23.43,36,12,28.491667,28.8,6.73248,10.491667,13.05,29.022544,8.438619,9630,29.077287,8.478628,0,27.916399,7.952362,3.209628,9.1,20.68,4.4,4.7,4,29.983461,8.483689,95_13_20,33.400000,14.150000,50,95_20_50,13_20_50,39.50,7.85,72439.949431,3,29.283535,8.333253,-6.149804,106.826983,-6.335585,106.807062,2026-01-18 11:07:51.000,533688.97
42168,2026-01-30,RIDE-042169,09:18:19,CNR1305788,Completed,Online,CID7740891,Go Sedan,Mangga Besar,Ciganjur,13.3,22.5,642000.0,38.78,4.3,4.5,Debit Card,No Cancellation,No Reason Provided,No Cancellation,No Reason Provided,0.0,No Reason Provided,2026-01-30 06:48:00,9,4,95,13,4,3.878000,3.683364,1503.8884,6.227359,1,0,0,7.071068e-01,-0.707107,-0.433884,-0.900969,3,30.380000,-0.20,4.400,0,0,4.3,8234,12,633.384615,12,13.372345,3.157000,2.564949,12.963135,3.446171,116.34,36,12,28.491667,28.8,6.73248,10.491667,13.05,28.969541,8.474192,8234,29.077287,8.478628,3,30.060481,8.487883,7.069147,8.8,19.35,4.3,4.5,3,28.674842,8.418815,95_13_9,22.500000,13.300000,18,95_9_18,13_9_18,19.10,4.80,16512.345679,3,29.283535,8.333253,-6.149804,106.826983,-6.335585,106.807062,2026-01-30 06:52:48.000,538444.60
46566,2026-02-02,RIDE-046567,07:49:01,CNR9046695,No Driver Found,Offline,CID9994944,Premier Sedan,Mangga Besar,Ciganjur,8.3,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Booked by Mistake,No Cancellation,Customer Unreachable,1.0,App Error,2026-02-02 08:06:00,7,1,95,13,4,2.965000,3.207613,562.6384,4.870318,1,0,0,9.659258e-01,-0.258819,0.781831,0.623490,3,29.066667,-0.20,4.400,0,0,4.3,5450,12,419.230769,12,12.933624,3.394508,2.564949,13.044044,3.403417,71.16,36,12,28.491667,28.8,6.73248,10.491667,13.05,29.018018,8.439284,5450,28.998560,8.431050,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,95_13_7,28.800000,8.300000,49,95_7_49,13_7_49,28.80,10.60,17380.352645,2,28.865348,8.671032,-6.149804,106.826983,-6.335585,106.807062,2026-02-02 08:16:36.000,413998.78
52013,2026-02-06,RIDE-052014,17:24:31,CNR8632340,Completed,Online,CID6795085,Motorcycle,Mangga Besar,Ciganjur,13.4,32.0,378000.0,43.90,3.7,4.9,Credit Card,No Cancellation,No Cancellation,Cancelled,Personal Issue,0.0,Route Problem,2026-02-06 02:53:00,17,0,95,13,4,2.438889,3.804438,1927.2100,6.625708,1,0,0,-9.659258e-01,-0.258819,0.000000,1.000000,3,29.028571,-0.75,4.300,1,0,0.0,11044,12,849.538462,12,12.842652,3.496508,2.564949,13.028996,3.402149,131.70,36,12,28.491667,28.8,6.73248,10.491667,13.05,28.995210,8.451911,11044,28.940847,8.432545,4,30.088452,8.531129,7.420544,8.6,18.13,3.7,4.9,3,28.674842,8.418815,95_13_17,32.000000,13.400000,24,95_17_24,13_17_24,42.10,9.80,8590.909091,2,28.865348,8.671032,-6.149804,106.826983,-6.335585,106.807062,2026-02-06 03:02:48.000,363362.96
69722,2026-02-18,RIDE-069723,12:12:48,CNR9572845,Completed,Online,CID6442163,Premier Sedan,Mangga Besar,Ciganjur,12.8,35.8,305000.0,10.59,3.2,4.9,UPI,No Cancellation,No Cancellation,Cancelled,Personal Issue,1.0,No Reason Provided,2026-02-18 10:02:00,12,1,95,13,4,0.814615,2.450143,112.1481,3.254228,0,0,0,1.224647e-16,-1.000000,0.781831,0.623490,2,29.400000,-0.75,4.050,1,0,0.0,7006,12,538.923077,12,12.628070,3.605498,2.564949,13.007516,3.414443,21.18,24,0,28.491667,28.8,6.73248,10.491667,13.05,29.176749,8.463389,7006,28.998560,8.431050,0,27.916399,7.952362,3.835192,8.1,15.68,3.2,4.9,3,28.674842,8.418815,95_13_12,33.433333,9.733333,12,95_12_12,13_12_12,25.00,4.10,28531.337699,1,29.069894,8.250120,-6.149804,106.826983,-6.335585,106.807062,2026-02-18 10:06:06.000,227480.71
70338,2026-02-18,RIDE-070339,20:10:47,CNR9923510,Completed,Online,CID2472670,Auto,Mangga Besar,Ciganjur,14.2,33.5,399000.0,16.23,3.9,4.2,UPI,Cancelled,Driver Taking Too Long,Cancelled,Traffic Issue,1.0,Vehicle Breakdown,2026-02-18 20:18:00,20,2,95,13,4,0.772857,2.846652,263.4129,4.028647,1,0,0,-8.660254e-01,0.500000,0.974928,-0.222521,3,30.111111,-0.30,4.050,1,0,0.0,9630,12,740.769231,12,12.896719,3.540959,2.564949,12.971801,3.437565,48.69,36,12,28.491667,28.8,6.73248,10.491667,13.05,29.022544,8.438619,9630,29.015911,8.453472,1,28.152500,8.043096,4.802878,8.1,16.38,3.9,4.2,3,28.674842,8.418815,95_13_20,33.400000,14.150000,10,95_20_10,13_20_10,18.10,12.80,24433.557869,2,28.865348,8.671032,-6.149804,106.826983,-6.335585,106.807062,2026-02-18 20:30:48.000,378005.64
102034,2026-03-12,RIDE-102035,22:25:01,CNR1110770,Completed,Online,CID4185745,eBike,Mangga Besar,Ciganjur,13.5,15.4,324000.0,10.69,4.6,4.8,UPI,Cancelled,Changed Mind,No Cancellation,Customer Unreachable,0.0,App Error,2026-03-12 20:34:00,22,2,95,13,4,0.464783,2.458734,114.2761,3.269557,0,0,1,-5.000000e-01,0.866025,0.974928,-0.222521,1,30.450000,-0.20,4.625,0,0,4.6,5441,12,418.538462,12,12.688502,2.797281,2.564949,12.964542,3.448399,10.69,12,0,28.491667,28.8,6.73248,10.491667,13.05,29.112571,8.432659,5441,29.015911,8.453472,0,27.916399,7.952362,3.855381,9.4,22.08,4.6,4.8,4,29.983461,8.483689,95_13_22,15.400000,13.500000,25,95_22_25,13_22_25,25.40,9.60,30027.803522,2,28.865348,8.671032,-6.149804,106.826983,-6.335585,106.807062,2026-03-12 20:43:36.000,350502.15
105724,2026-03-15,RIDE-105725,21:28:27,CNR9391988,Completed,Online,CID5113242,Car,Mangga Besar,Ciganjur,14.1,22.0,405000.0,40.14,3.7,4.8,UPI,No Cancellation,No Cancellation,Cancelled,Customer Unreachable,0.0,App Error,2026-03-15 10:04:00,21,4,95,13,4,1.824545,3.716981,1611.2196,6.335614,0,0,0,-7.071068e-01,0.707107,-0.433884,-0.900969,1,29.081818,-0.75,4.250,1,0,0.0,8103,12,623.307692,12,12.911645,3.135494,2.564949,12.942369,3.403921,40.14,12,0,28.491667,28.8,6.73248,10.491667,13.05,29.006319,8.386326,8103,29.077287,8.478628,3,30.060481,8.487883,7.166143,8.5,17.76,3.7,4.8,3,28.674842,8.418815,95_13_21,22.000000,14.100000,28,95_21_28,13_21_28,40.90,13.70,10064.612326,2,28.865348,8.671032,-6.149804,106.826983,-6.335585,106.807062,2026-03-15 10:17:42.000,356514.48

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 97 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   user_id                            150000 non-null  object
 2   Time                               150000 non-null  object
 3   Booking ID                         150000 non-null  object
 4   Booking Status                     150000 non-null  object
 5   Driver Status                      150000 non-null  object
 6   Customer ID                        150000 non-null  object
 7   Vehicle Type                       150000 non-null  object
 8   Pickup Location                    150000 non-null  object
 9   Drop Location                      150000 non-null  object
 10  Avg VTAT                           150000 non-null  float64
 11  Avg CTAT                           150000 non-null  float64
 12  Booking Value                      150000 non-null  float64
 13  Ride Distance                      150000 non-null  float64
 14  Driver Ratings                     150000 non-null  float64
 15  Customer Rating                    150000 non-null  float64
 16  Payment Method                     150000 non-null  object
 17  Cancelled Rides by Customer        150000 non-null  object
 18  Reason for cancelling by Customer  150000 non-null  object
 19  Cancelled Rides by Driver          150000 non-null  object
 20  Driver Cancellation Reason         150000 non-null  object
 21  Incomplete Rides                   150000 non-null  float64
 22  Incomplete Rides Reason            150000 non-null  object
 23  Datetime                           150000 non-null  datetime64[ns]
 24  hour                               150000 non-null  int32
 25  day_of_week                        150000 non-null  int32
 26  Pickup Encoded                     150000 non-null  int64
 27  Drop Encoded                       150000 non-null  int64
 28  route_cluster                      150000 non-null  int32
 29  distance_per_hour                  150000 non-null  float64
 30  log_distance                       150000 non-null  float64
 31  distance_squared                   150000 non-null  float64
 32  distance_sqrt                      150000 non-null  float64
 33  is_peak_hour                       150000 non-null  int64
 34  is_weekend                         150000 non-null  int64
 35  is_night                           150000 non-null  int64
 36  hour_sin                           150000 non-null  float64
 37  hour_cos                           150000 non-null  float64
 38  day_sin                            150000 non-null  float64
 39  day_cos                            150000 non-null  float64
 40  traffic_score                      150000 non-null  int64
 41  route_avg_ctat_safe                150000 non-null  float64
 42  rating_diff                        150000 non-null  float64
 43  avg_rating                         150000 non-null  float64
 44  low_driver_rating                  150000 non-null  int64
 45  low_customer_rating                150000 non-null  int64
 46  driver_score                       150000 non-null  float64
 47  hourly_demand                      150000 non-null  int64
 48  route_demand                       150000 non-null  int64
 49  demand_pressure                    150000 non-null  float64
 50  route_count                        150000 non-null  int64
 51  log_price                          150000 non-null  float64
 52  log_ctat                           150000 non-null  float64
 53  log_route_count                    150000 non-null  float64
 54  log_route_price                    150000 non-null  float64
 55  log_route_ctat                     150000 non-null  float64
 56  time_distance_interaction          150000 non-null  float64
 57  route_complexity                   150000 non-null  int64
 58  peak_pressure                      150000 non-null  int64
 59  route_ctat_mean                    150000 non-null  float64
 60  route_ctat_median                  150000 non-null  float64
 61  route_ctat_std                     150000 non-null  float64
 62  route_vtat_mean                    150000 non-null  float64
 63  route_vtat_median                  150000 non-null  float64
 64  hour_avg_ctat                      150000 non-null  float64
 65  hour_avg_vtat                      150000 non-null  float64
 66  hour_demand                        150000 non-null  int64
 67  dow_avg_ctat                       150000 non-null  float64
 68  dow_avg_vtat                       150000 non-null  float64
 69  distance_bin                       150000 non-null  int64
 70  dist_bin_ctat                      150000 non-null  float64
 71  dist_bin_vtat                      150000 non-null  float64
 72  log_distance_v2                    150000 non-null  float64
 73  rating_sum                         150000 non-null  float64
 74  rating_mult                        150000 non-null  float64
 75  rating_min                         150000 non-null  float64
 76  rating_max                         150000 non-null  float64
 77  rating_bucket                      150000 non-null  int64
 78  rating_bucket_ctat                 150000 non-null  float64
 79  rating_bucket_vtat                 150000 non-null  float64
 80  route_hour_key                     150000 non-null  object
 81  route_hour_ctat                    150000 non-null  float64
 82  route_hour_vtat                    150000 non-null  float64
 83  minute                             150000 non-null  int32
 84  pickup_key                         150000 non-null  object
 85  drop_key                           150000 non-null  object
 86  estimated_pickup_time_minute       150000 non-null  float64
 87  estimated_drop_time_minute         150000 non-null  float64
 88  price_per_km                       150000 non-null  float64
 89  price_bucket                       150000 non-null  int64
 90  price_bucket_ctat                  150000 non-null  float64
 91  price_bucket_vtat                  150000 non-null  float64
 92  pickup_lat                         150000 non-null  float64
 93  pickup_lon                         150000 non-null  float64
 94  drop_lat                           150000 non-null  float64
 95  drop_lon                           150000 non-null  float64
 96  completed_at                       150000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(55), int32(4), int64(17), object(19)
memory usage: 108.7+ MB

In [4]:
df['Booking Value']

0          99000.0
1         114000.0
2         414000.0
3         414000.0
4         414000.0
            ...
149995    440000.0
149996    279000.0
149997      1855.0
149998    520000.0
149999    571000.0
Name: Booking Value, Length: 150000, dtype: float64

In [5]:
df["estimated_fare"] = df["Booking Value"]

In [6]:
df.isnull().sum()

Date              0
user_id           0
Time              0
Booking ID        0
Booking Status    0
                 ..
pickup_lon        0
drop_lat          0
drop_lon          0
completed_at      0
estimated_fare    0
Length: 98, dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 98 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   user_id                            150000 non-null  object
 2   Time                               150000 non-null  object
 3   Booking ID                         150000 non-null  object
 4   Booking Status                     150000 non-null  object
 5   Driver Status                      150000 non-null  object
 6   Customer ID                        150000 non-null  object
 7   Vehicle Type                       150000 non-null  object
 8   Pickup Location                    150000 non-null  object
 9   Drop Location                      150000 non-null  object
 10  Avg VTAT                           150000 non-null  float64
 11  Avg CTAT                           150000 non-null  float64
 12  Booking Value                      150000 non-null  float64
 13  Ride Distance                      150000 non-null  float64
 14  Driver Ratings                     150000 non-null  float64
 15  Customer Rating                    150000 non-null  float64
 16  Payment Method                     150000 non-null  object
 17  Cancelled Rides by Customer        150000 non-null  object
 18  Reason for cancelling by Customer  150000 non-null  object
 19  Cancelled Rides by Driver          150000 non-null  object
 20  Driver Cancellation Reason         150000 non-null  object
 21  Incomplete Rides                   150000 non-null  float64
 22  Incomplete Rides Reason            150000 non-null  object
 23  Datetime                           150000 non-null  datetime64[ns]
 24  hour                               150000 non-null  int32
 25  day_of_week                        150000 non-null  int32
 26  Pickup Encoded                     150000 non-null  int64
 27  Drop Encoded                       150000 non-null  int64
 28  route_cluster                      150000 non-null  int32
 29  distance_per_hour                  150000 non-null  float64
 30  log_distance                       150000 non-null  float64
 31  distance_squared                   150000 non-null  float64
 32  distance_sqrt                      150000 non-null  float64
 33  is_peak_hour                       150000 non-null  int64
 34  is_weekend                         150000 non-null  int64
 35  is_night                           150000 non-null  int64
 36  hour_sin                           150000 non-null  float64
 37  hour_cos                           150000 non-null  float64
 38  day_sin                            150000 non-null  float64
 39  day_cos                            150000 non-null  float64
 40  traffic_score                      150000 non-null  int64
 41  route_avg_ctat_safe                150000 non-null  float64
 42  rating_diff                        150000 non-null  float64
 43  avg_rating                         150000 non-null  float64
 44  low_driver_rating                  150000 non-null  int64
 45  low_customer_rating                150000 non-null  int64
 46  driver_score                       150000 non-null  float64
 47  hourly_demand                      150000 non-null  int64
 48  route_demand                       150000 non-null  int64
 49  demand_pressure                    150000 non-null  float64
 50  route_count                        150000 non-null  int64
 51  log_price                          150000 non-null  float64
 52  log_ctat                           150000 non-null  float64
 53  log_route_count                    150000 non-null  float64
 54  log_route_price                    150000 non-null  float64
 55  log_route_ctat                     150000 non-null  float64
 56  time_distance_interaction          150000 non-null  float64
 57  route_complexity                   150000 non-null  int64
 58  peak_pressure                      150000 non-null  int64
 59  route_ctat_mean                    150000 non-null  float64
 60  route_ctat_median                  150000 non-null  float64
 61  route_ctat_std                     150000 non-null  float64
 62  route_vtat_mean                    150000 non-null  float64
 63  route_vtat_median                  150000 non-null  float64
 64  hour_avg_ctat                      150000 non-null  float64
 65  hour_avg_vtat                      150000 non-null  float64
 66  hour_demand                        150000 non-null  int64
 67  dow_avg_ctat                       150000 non-null  float64
 68  dow_avg_vtat                       150000 non-null  float64
 69  distance_bin                       150000 non-null  int64
 70  dist_bin_ctat                      150000 non-null  float64
 71  dist_bin_vtat                      150000 non-null  float64
 72  log_distance_v2                    150000 non-null  float64
 73  rating_sum                         150000 non-null  float64
 74  rating_mult                        150000 non-null  float64
 75  rating_min                         150000 non-null  float64
 76  rating_max                         150000 non-null  float64
 77  rating_bucket                      150000 non-null  int64
 78  rating_bucket_ctat                 150000 non-null  float64
 79  rating_bucket_vtat                 150000 non-null  float64
 80  route_hour_key                     150000 non-null  object
 81  route_hour_ctat                    150000 non-null  float64
 82  route_hour_vtat                    150000 non-null  float64
 83  minute                             150000 non-null  int32
 84  pickup_key                         150000 non-null  object
 85  drop_key                           150000 non-null  object
 86  estimated_pickup_time_minute       150000 non-null  float64
 87  estimated_drop_time_minute         150000 non-null  float64
 88  price_per_km                       150000 non-null  float64
 89  price_bucket                       150000 non-null  int64
 90  price_bucket_ctat                  150000 non-null  float64
 91  price_bucket_vtat                  150000 non-null  float64
 92  pickup_lat                         150000 non-null  float64
 93  pickup_lon                         150000 non-null  float64
 94  drop_lat                           150000 non-null  float64
 95  drop_lon                           150000 non-null  float64
 96  completed_at                       150000 non-null  datetime64[ns]
 97  estimated_fare                     150000 non-null  float64
dtypes: datetime64[ns](2), float64(56), int32(4), int64(17), object(19)
memory usage: 109.9+ MB

## Split data into X and y & Feature Engineering & Data encoding

#### Deleted column features

    # Redundant data features
    'log_distance', 'distance_squared', 'distance_sqrt', 'log_distance_v2',
    'log_ctat', 'log_route_count', 'log_route_ctat'

    # Post-booking features that cause leakage
    'Booking Status', 'Driver Status', 'Cancelled Rides by Customer', 
    'Reason for cancelling by Customer', 'Cancelled Rides by Driver', 
    'Driver Cancellation Reason', 'Incomplete Rides', 'Incomplete Rides Reason',

In [8]:
from sklearn.model_selection import train_test_split

df_clean = df.copy()

# Define leakage features
leakage_and_ids = [
    
     # Original IDs and targets
    'Booking Value', 'estimated_fare', 'log_price', 'price_per_km', 'log_route_price',
    'Booking ID', 'user_id', 'Customer ID', 'route_hour_key', 'pickup_key', 'drop_key', 
    'Date', 'Time', 'Datetime', 'completed_at',
    
    # Post-booking features that cause leakage
    'Booking Status', 'Driver Status', 'Cancelled Rides by Customer', 
    'Reason for cancelling by Customer', 'Cancelled Rides by Driver', 
    'Driver Cancellation Reason', 'Incomplete Rides', 'Incomplete Rides Reason',

    # Redundant data features
    'log_distance', 'distance_squared', 'distance_sqrt', 'log_distance_v2',
    'log_ctat', 'log_route_count', 'log_route_ctat'

]

# Split to features and target
X = df_clean.drop(columns=leakage_and_ids)
y = df_clean["estimated_fare"]


# Label encoding for categorical features
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in X.columns:
    if X[col].dtype == 'object':
        X[col] = le.fit_transform(X[col])

# Show data after encoding
X.head()

# Split to train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (120000, 68)
X_test shape: (30000, 68)

In [9]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120000 entries, 104025 to 121958
Data columns (total 68 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Vehicle Type                  120000 non-null  int64
 1   Pickup Location               120000 non-null  int64
 2   Drop Location                 120000 non-null  int64
 3   Avg VTAT                      120000 non-null  float64
 4   Avg CTAT                      120000 non-null  float64
 5   Ride Distance                 120000 non-null  float64
 6   Driver Ratings                120000 non-null  float64
 7   Customer Rating               120000 non-null  float64
 8   Payment Method                120000 non-null  int64
 9   hour                          120000 non-null  int32
 10  day_of_week                   120000 non-null  int32
 11  Pickup Encoded                120000 non-null  int64
 12  Drop Encoded                  120000 non-null  int64
 13  route_cluster                 120000 non-null  int32
 14  distance_per_hour             120000 non-null  float64
 15  is_peak_hour                  120000 non-null  int64
 16  is_weekend                    120000 non-null  int64
 17  is_night                      120000 non-null  int64
 18  hour_sin                      120000 non-null  float64
 19  hour_cos                      120000 non-null  float64
 20  day_sin                       120000 non-null  float64
 21  day_cos                       120000 non-null  float64
 22  traffic_score                 120000 non-null  int64
 23  route_avg_ctat_safe           120000 non-null  float64
 24  rating_diff                   120000 non-null  float64
 25  avg_rating                    120000 non-null  float64
 26  low_driver_rating             120000 non-null  int64
 27  low_customer_rating           120000 non-null  int64
 28  driver_score                  120000 non-null  float64
 29  hourly_demand                 120000 non-null  int64
 30  route_demand                  120000 non-null  int64
 31  demand_pressure               120000 non-null  float64
 32  route_count                   120000 non-null  int64
 33  time_distance_interaction     120000 non-null  float64
 34  route_complexity              120000 non-null  int64
 35  peak_pressure                 120000 non-null  int64
 36  route_ctat_mean               120000 non-null  float64
 37  route_ctat_median             120000 non-null  float64
 38  route_ctat_std                120000 non-null  float64
 39  route_vtat_mean               120000 non-null  float64
 40  route_vtat_median             120000 non-null  float64
 41  hour_avg_ctat                 120000 non-null  float64
 42  hour_avg_vtat                 120000 non-null  float64
 43  hour_demand                   120000 non-null  int64
 44  dow_avg_ctat                  120000 non-null  float64
 45  dow_avg_vtat                  120000 non-null  float64
 46  distance_bin                  120000 non-null  int64
 47  dist_bin_ctat                 120000 non-null  float64
 48  dist_bin_vtat                 120000 non-null  float64
 49  rating_sum                    120000 non-null  float64
 50  rating_mult                   120000 non-null  float64
 51  rating_min                    120000 non-null  float64
 52  rating_max                    120000 non-null  float64
 53  rating_bucket                 120000 non-null  int64
 54  rating_bucket_ctat            120000 non-null  float64
 55  rating_bucket_vtat            120000 non-null  float64
 56  route_hour_ctat               120000 non-null  float64
 57  route_hour_vtat               120000 non-null  float64
 58  minute                        120000 non-null  int32
 59  estimated_pickup_time_minute  120000 non-null  float64
 60  estimated_drop_time_minute    120000 non-null  float64
 61  price_bucket                  120000 non-null  int64
 62  price_bucket_ctat             120000 non-null  float64
 63  price_bucket_vtat             120000 non-null  float64
 64  pickup_lat                    120000 non-null  float64
 65  pickup_lon                    120000 non-null  float64
 66  drop_lat                      120000 non-null  float64
 67  drop_lon                      120000 non-null  float64
dtypes: float64(43), int32(4), int64(21)
memory usage: 61.3 MB

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 68 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Vehicle Type                  150000 non-null  int64
 1   Pickup Location               150000 non-null  int64
 2   Drop Location                 150000 non-null  int64
 3   Avg VTAT                      150000 non-null  float64
 4   Avg CTAT                      150000 non-null  float64
 5   Ride Distance                 150000 non-null  float64
 6   Driver Ratings                150000 non-null  float64
 7   Customer Rating               150000 non-null  float64
 8   Payment Method                150000 non-null  int64
 9   hour                          150000 non-null  int32
 10  day_of_week                   150000 non-null  int32
 11  Pickup Encoded                150000 non-null  int64
 12  Drop Encoded                  150000 non-null  int64
 13  route_cluster                 150000 non-null  int32
 14  distance_per_hour             150000 non-null  float64
 15  is_peak_hour                  150000 non-null  int64
 16  is_weekend                    150000 non-null  int64
 17  is_night                      150000 non-null  int64
 18  hour_sin                      150000 non-null  float64
 19  hour_cos                      150000 non-null  float64
 20  day_sin                       150000 non-null  float64
 21  day_cos                       150000 non-null  float64
 22  traffic_score                 150000 non-null  int64
 23  route_avg_ctat_safe           150000 non-null  float64
 24  rating_diff                   150000 non-null  float64
 25  avg_rating                    150000 non-null  float64
 26  low_driver_rating             150000 non-null  int64
 27  low_customer_rating           150000 non-null  int64
 28  driver_score                  150000 non-null  float64
 29  hourly_demand                 150000 non-null  int64
 30  route_demand                  150000 non-null  int64
 31  demand_pressure               150000 non-null  float64
 32  route_count                   150000 non-null  int64
 33  time_distance_interaction     150000 non-null  float64
 34  route_complexity              150000 non-null  int64
 35  peak_pressure                 150000 non-null  int64
 36  route_ctat_mean               150000 non-null  float64
 37  route_ctat_median             150000 non-null  float64
 38  route_ctat_std                150000 non-null  float64
 39  route_vtat_mean               150000 non-null  float64
 40  route_vtat_median             150000 non-null  float64
 41  hour_avg_ctat                 150000 non-null  float64
 42  hour_avg_vtat                 150000 non-null  float64
 43  hour_demand                   150000 non-null  int64
 44  dow_avg_ctat                  150000 non-null  float64
 45  dow_avg_vtat                  150000 non-null  float64
 46  distance_bin                  150000 non-null  int64
 47  dist_bin_ctat                 150000 non-null  float64
 48  dist_bin_vtat                 150000 non-null  float64
 49  rating_sum                    150000 non-null  float64
 50  rating_mult                   150000 non-null  float64
 51  rating_min                    150000 non-null  float64
 52  rating_max                    150000 non-null  float64
 53  rating_bucket                 150000 non-null  int64
 54  rating_bucket_ctat            150000 non-null  float64
 55  rating_bucket_vtat            150000 non-null  float64
 56  route_hour_ctat               150000 non-null  float64
 57  route_hour_vtat               150000 non-null  float64
 58  minute                        150000 non-null  int32
 59  estimated_pickup_time_minute  150000 non-null  float64
 60  estimated_drop_time_minute    150000 non-null  float64
 61  price_bucket                  150000 non-null  int64
 62  price_bucket_ctat             150000 non-null  float64
 63  price_bucket_vtat             150000 non-null  float64
 64  pickup_lat                    150000 non-null  float64
 65  pickup_lon                    150000 non-null  float64
 66  drop_lat                      150000 non-null  float64
 67  drop_lon                      150000 non-null  float64
dtypes: float64(43), int32(4), int64(21)
memory usage: 75.5 MB

In [11]:
X_train.head(2)

,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Ride Distance,Driver Ratings,Customer Rating,Payment Method,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_ctat,route_hour_vtat,minute,estimated_pickup_time_minute,estimated_drop_time_minute,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon
104025,2,89,116,12.0,44.1,22.86,4.9,4.2,0,19,0,89,116,1,1.143000,1,0,0,-0.965926,0.258819,0.000000,1.00000,3,17.966667,0.45,4.55,0,0,0.0,11047,7,1380.875,7,68.58,21,7,32.528571,38.20,12.327708,7.628571,9.20,29.012085,8.428614,11047,28.940847,8.432545,2,29.119842,8.707975,9.1,20.58,4.2,4.9,4,29.983461,8.483689,44.10,12.00,23,16.3,6.50,1,29.069894,8.250120,-6.301672,106.779691,-6.210382,106.841227
5415,0,71,156,6.1,28.8,23.72,4.3,4.5,2,8,6,71,156,3,2.635556,1,1,0,0.866025,-0.500000,-0.781831,0.62349,1,29.026393,-0.20,4.40,0,0,4.3,6861,4,1372.200,4,23.72,4,4,32.350000,28.85,7.033491,10.650000,11.45,29.180251,8.506850,6861,29.139191,8.448285,2,29.119842,8.707975,8.8,19.35,4.3,4.5,3,28.674842,8.418815,35.85,9.85,54,44.8,4.85,2,28.865348,8.671032,-6.185082,106.831105,-6.206499,106.754106

## Scaling Data

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train shape:", X_train_scaled.shape)
print("X_test shape:", X_test_scaled.shape)

X_train shape: (120000, 68)
X_test shape: (30000, 68)

## Machine learning models prediction - Supervised Learning
### **Machine learning prediction method is regression because the data is linear**

In [13]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error


# Define models
MODELS = {
    "Random Forest": RandomForestRegressor(random_state=42, n_jobs=-1),
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42)
}

# Define params
PARAMS_GRID = {
    "Random Forest": {
        "n_estimators": [100, 150],
        "max_depth": [10, 15],
        "min_samples_split": [3, 5],
        "min_samples_leaf": [1, 2],
        "max_features": ['sqrt']
    },
    "Decision Tree": {
        "max_depth": [10, 15],
        "min_samples_split": [3, 5],
        "min_samples_leaf": [1, 2]
    }
}

# Create table comparing model performance
metrics_list = []

# Train and evaluate each models
for model_name, model in MODELS.items():
    print(f"Training {model_name}...")
    params = PARAMS_GRID.get(model_name) # Define params for grid search

    if params:
        print(f"Running Grid Search for {model_name}...")
        grid_search = GridSearchCV(model,
                                   params,
                                   cv=5,
                                   scoring='r2',
                                   n_jobs=-1,
                                   verbose=1)
        grid_search.fit(X_train_scaled, y_train)

        # Get best model from grid search
        best_model = grid_search.best_estimator_
        y_pred = grid_search.predict(X_test_scaled)
        print(f"Best params for {model_name}: {grid_search.best_params_}")
    else:
        # Standard linear regression bypasss grid search
        print(f"No hyperparams defined for {model_name}, training with default params...")
        model.fit(X_train_scaled, y_train)
        best_model = model
        y_pred = model.predict(X_test_scaled)

    # Overwrite the raw blueprint wihth fully trained
    MODELS[model_name] = best_model

    # Define y_pred and evaluate
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)

    print("\nEvaluation Metrics:")
    print(f" MSE: {mse:.3f}")
    print(f"  R2: {r2:.3f}")
    print(f"  MAE: {mae:.3f}")
    print(f"  MAPE: {mape:.3f}%")


    # Show feature importance for best model
    if model_name in ["Random Forest", "Decision Tree", "Linear Regression"]:
        feature_importance = best_model.feature_importances_ if model_name != "Linear Regression" else best_model.coef_
        feature_importance_df = pd.DataFrame({
            "Feature": X.columns,
            "Importance": feature_importance
        })
        feature_importance_df = feature_importance_df.sort_values(by="Importance", ascending=False)
        print(f"\nFeature importance for {model_name}:")
        print(feature_importance_df.head(10))


    metrics_list.append({
        "Model": model_name,
        "MSE": mse,
        "R2": r2,
        "MAE": mae,
        "MAPE": mape
    })
    print("\n" + "="*50 + "\n")

    # 🎯 TARGET IMPLEMENTATION: Map the 30k predictions back to the 150k rows
    column_name = f"pred_fare_{model_name.lower().replace(' ', '_')}"
    df_clean.loc[X_test.index, column_name] = y_pred

# Create metrics table
metrics_df = pd.DataFrame(metrics_list)

# Add rank column to see comparison between models
metrics_df['Rank'] = metrics_df['R2'].rank(ascending=False, method='min').astype(int)
metrics_df = metrics_df.sort_values(by='Rank')

print("Final Model Performance Comparison Table:")
print(metrics_df[["Rank", "Model", "MSE", "R2", "MAE", "MAPE"]].to_string(index=False))
print("\n" + "="*50 + "\n")
print("\nResult contained model prediction to dataframe")
print(df_clean[['estimated_fare', 'pred_fare_random_forest', 'pred_fare_linear_regression', 'pred_fare_decision_tree']].head(10))

print("\n" + "="*50 + "\n")

Training Random Forest...
Running Grid Search for Random Forest...
Fitting 5 folds for each of 16 candidates, totalling 80 fits
Best params for Random Forest: {'max_depth': 15, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 150}

Evaluation Metrics:
 MSE: 2702089635.498
  R2: 0.925
  MAE: 34079.787
  MAPE: 3.932%

Feature importance for Random Forest:
              Feature  Importance
63  price_bucket_vtat    0.343667
61       price_bucket    0.293963
62  price_bucket_ctat    0.239689
48      dist_bin_vtat    0.013730
4            Avg CTAT    0.009517
52         rating_max    0.008568
7     Customer Rating    0.008007
5       Ride Distance    0.007422
50        rating_mult    0.007088
8      Payment Method    0.005829

==================================================

Training Linear Regression...
No hyperparams defined for Linear Regression, training with default params...

Evaluation Metrics:
 MSE: 2830515277.818
  R2: 0.921
  MAE: 36692.572
  MAPE: 3.252%

Feature importance for Linear Regression:
            Feature    Importance
49       rating_sum  1.066869e+18
7   Customer Rating  5.131915e+17
6    Driver Ratings  5.097096e+17
12     Drop Encoded  2.511097e+17
32      route_count  1.086280e+17
43      hour_demand  7.883892e+15
1   Pickup Location  7.133597e+14
61     price_bucket  1.852708e+05
10      day_of_week  2.627426e+04
48    dist_bin_vtat  9.600000e+03

==================================================

Training Decision Tree...
Running Grid Search for Decision Tree...
Fitting 5 folds for each of 8 candidates, totalling 40 fits
Best params for Decision Tree: {'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 5}

Evaluation Metrics:
 MSE: 2785116204.941
  R2: 0.922
  MAE: 33929.922
  MAPE: 3.188%

Feature importance for Decision Tree:
                       Feature  Importance
61                price_bucket    0.797958
62           price_bucket_ctat    0.192776
48               dist_bin_vtat    0.003636
5                Ride Distance    0.001157
16                  is_weekend    0.000833
20                     day_sin    0.000438
60  estimated_drop_time_minute    0.000190
38              route_ctat_std    0.000190
56             route_hour_ctat    0.000154
36             route_ctat_mean    0.000144

==================================================

Final Model Performance Comparison Table:
 Rank             Model          MSE       R2          MAE     MAPE
    1     Random Forest 2.702090e+09 0.924748 34079.786765 3.931728
    2     Decision Tree 2.785116e+09 0.922436 33929.922056 3.188475
    3 Linear Regression 2.830515e+09 0.921172 36692.572355 3.251847

==================================================


Result contained model prediction to dataframe
   estimated_fare  pred_fare_random_forest  pred_fare_linear_regression  \
0         99000.0             38698.654071                 17472.539114
1        114000.0                      NaN                          NaN
2        414000.0                      NaN                          NaN
3        414000.0                      NaN                          NaN
4        414000.0            413958.716013                412638.835641
5        735000.0                      NaN                          NaN
6        414000.0                      NaN                          NaN
7        414000.0                      NaN                          NaN
8        414000.0                      NaN                          NaN
9        414000.0                      NaN                          NaN

   pred_fare_decision_tree
0             33799.332244
1                      NaN
2                      NaN
3                      NaN
4            414000.000000
5                      NaN
6                      NaN
7                      NaN
8                      NaN
9                      NaN

==================================================

## Data Science -> Implement machine learning prediction to Dataframe

In [14]:
print("\nImplementing rounding to predicted fare columns for better readability and consistency with original fare values...")
pred_cols = [
    "pred_fare_random_forest",
    "pred_fare_linear_regression",
    "pred_fare_decision_tree"
]

# apply rounding to the predicted fare columns
df_clean[pred_cols] = df_clean[pred_cols].round(2)

# Data science: Predict all rows to implement in production
X_scaled_all = scaler.transform(X)

df_clean['pred_fare_random_forest'] = MODELS['Random Forest'].predict(X_scaled_all).round(2)
df_clean['pred_fare_linear_regression'] = MODELS['Linear Regression'].predict(X_scaled_all).round(2)
df_clean['pred_fare_decision_tree'] = MODELS['Decision Tree'].predict(X_scaled_all).round(2)

print("\nResult contained model prediction to dataframe (No NaNs):")
df_clean[['Booking Value', 'pred_fare_random_forest', 'pred_fare_linear_regression', 'pred_fare_decision_tree']].head(10)

Implementing rounding to predicted fare columns for better readability and consistency with original fare values...

Result contained model prediction to dataframe (No NaNs):

,Booking Value,pred_fare_random_forest,pred_fare_linear_regression,pred_fare_decision_tree
0,99000.0,38698.65,17472.54,33799.33
1,114000.0,188314.36,221970.93,205352.14
2,414000.0,413999.88,418069.66,414000.00
3,414000.0,413999.46,414438.88,414000.00
4,414000.0,413958.72,412638.84,414000.00
5,735000.0,578503.33,550556.14,542121.75
6,414000.0,413997.90,406118.88,414000.00
7,414000.0,413999.63,407496.01,414000.00
8,414000.0,413999.61,406131.94,414000.00
9,414000.0,413999.68,410888.35,414000.00

In [22]:
df_clean[['Booking Value', 'pred_fare_random_forest', 'pred_fare_linear_regression', 'pred_fare_decision_tree']].sample(20)

,Booking Value,pred_fare_random_forest,pred_fare_linear_regression,pred_fare_decision_tree
59991,414000.0,414000.11,415101.75,414000.00
68705,414000.0,414000.09,406986.76,414000.00
41454,135000.0,207335.08,214836.66,213208.99
103622,917.0,7683.02,15521.77,8223.88
122358,422000.0,527030.13,566403.39,538164.16
94202,80000.0,39489.03,29600.20,25310.67
127581,609000.0,550761.55,543789.70,539586.35
73610,211000.0,210406.97,218952.41,213208.99
89063,414000.0,414000.00,409050.37,414000.00
89469,375000.0,367794.04,404668.45,365797.01
63152,737.0,8736.95,7404.07,3204.42
121880,314000.0,243869.93,196255.31,211784.48
145433,98000.0,31649.80,6452.72,9507.14
28290,276000.0,209349.94,216552.42,214289.47
8920,432000.0,523853.34,549125.80,545268.67
92837,428000.0,519360.97,547224.79,538164.16
107770,388000.0,365176.93,382435.29,365379.31
53138,508000.0,537404.86,541137.83,538164.16
89461,1634.0,11270.94,18380.90,11902.59
79745,414000.0,413999.50,405010.57,414000.00

In [23]:
df_clean = df_clean.drop(columns=['estimated_fare', 'pred_fare_linear_regression', 'pred_fare_decision_tree'])
df_clean = df_clean.rename(columns={"pred_fare_random_forest": "estimated_fare"})
df_clean.head(10)

,Date,user_id,Time,Booking ID,Booking Status,Driver Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon,completed_at,estimated_fare
0,2026-01-01,RIDE-000001,00:19:34,CNR4352144,Completed,Online,CID8362794,Motorcycle,Pasar Baru,Cilandak Timur,10.8,38.9,99000.0,37.98,4.8,4.8,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation,2026-01-01 00:00:00,0,0,110,18,4,4.312727,3.663049,1442.4804,6.162792,0,0,1,0.000000,1.000000,0.0,1.0,1,29.026393,0.0,4.625,0,0,4.8,1373,5,228.833333,5,11.502885,3.686376,1.791759,12.700787,3.394508,37.98,5,0,30.820000,31.20,9.496684,9.620000,10.80,29.024763,8.400510,1373,28.940847,8.432545,3,30.060481,8.487883,7.010743,9.6,23.04,4.8,4.8,4,29.983461,8.483689,110_18_0,38.9,10.8,19,110_0_19,18_0_19,18.90,11.55,2599.789916,0,29.126926,8.283577,-6.164901,106.833467,-6.289466,106.812477,2026-01-01 00:11:33,38698.65
1,2026-01-01,RIDE-000002,01:35:18,CNR9147645,Completed,Online,CID8300238,Car,Kali Anyar,Rawamangun,8.5,15.1,114000.0,39.29,4.2,4.1,Uber Wallet,No Cancellation,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,No Reason Provided,2026-01-01 00:01:00,1,0,47,147,3,4.312727,3.696103,1543.7041,6.268174,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,0.1,4.150,0,1,4.2,1360,2,453.333333,2,11.643962,2.778819,1.098612,12.700787,3.394508,39.29,2,0,18.300000,18.30,4.525483,7.000000,7.00,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.105852,8.3,17.22,4.1,4.2,3,28.674842,8.418815,47_147_1,15.1,8.5,35,47_1_35,147_1_35,27.00,3.40,2894.135567,1,29.069894,8.250120,-7.550534,110.819452,-6.195928,106.884725,2026-01-01 00:04:24,188314.36
2,2026-01-01,RIDE-000003,01:37:50,CNR1009222,Cancelled by Driver,Online,CID2030746,Go Sedan,Serdang,Pengadegan,7.4,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Traffic Issue,0.0,App Error,2026-01-01 00:02:00,1,0,147,125,1,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,4.3,1360,4,272.000000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,28.750000,28.80,0.100000,10.900000,9.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,147_125_1,28.8,7.4,37,147_1_37,125_1_37,20.10,8.60,17380.352645,2,28.865348,8.671032,3.034065,101.705568,-6.248914,106.854349,2026-01-01 00:10:36,413999.88
3,2026-01-01,RIDE-000004,01:48:03,CNR2740479,Cancelled by Driver,Online,CID3231181,Auto,Tanah Tinggi,Kampung Rawa,5.6,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,Personal Issue,0.0,No Reason Provided,2026-01-01 00:03:00,1,0,160,61,2,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,4.3,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.914286,25.90,3.223057,6.571429,5.60,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,160_61_1,28.8,5.6,48,160_1_48,61_1_48,28.40,5.80,17380.352645,2,28.865348,8.671032,57.506636,-5.003837,-6.179512,106.855659,2026-01-01 00:08:48,413999.46
4,2026-01-01,RIDE-000005,01:49:56,CNR7650148,Cancelled by Driver,Online,CID3381661,Go Sedan,Jati,Batu Ceper,6.2,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Wrong Pickup Location,Cancelled,Wrong Location,1.0,Route Problem,2026-01-01 00:04:00,1,0,40,2,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,0.0,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,23.542857,20.60,6.484303,5.514286,6.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,40_2_1,28.8,6.2,49,40_1_49,2_1_49,31.57,6.60,17380.352645,2,28.865348,8.671032,-7.689434,-39.006074,-6.172027,106.665287,2026-01-01 00:10:36,413958.72
5,2026-01-01,RIDE-000006,01:53:01,CNR8140858,Completed,Online,CID9268400,Car,Pulo Gadung,Semper Barat,8.1,42.6,735000.0,39.39,4.3,4.7,UPI,No Cancellation,No Reason Provided,Cancelled,Customer Unreachable,0.0,Ride Cancelled Midway,2026-01-01 00:05:00,1,0,134,151,1,4.312727,3.698582,1551.5721,6.276145,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.4,4.500,0,0,0.0,1360,10,123.636364,10,13.507627,3.775057,2.397895,12.700787,3.394508,39.39,10,0,29.200000,28.80,8.910044,10.060000,9.90,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.113002,9.0,20.21,4.3,4.7,3,28.674842,8.418815,134_151_1,42.6,8.1,53,134_1_53,151_1_53,28.80,8.05,18612.306913,3,29.283535,8.333253,-6.191109,106.890605,-6.123854,106.924351,2026-01-01 00:13:03,578503.33
6,2026-01-01,RIDE-000007,02:14:50,CNR8839592,Cancelled by Driver,Online,CID6577042,Motorcycle,Kelapa Gading Timur,Rorotan,11.8,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Changed Mind,Cancelled,No Reason Provided,0.0,App Error,2026-01-01 00:06:00,2,0,75,149,3,4.312727,3.207613,562.6384,4.870318,0,0,1,0.500000,0.866025,0.0,1.0,1,29.026393,-0.2,4.400,0,0,0.0,1339,6,191.285714,6,12.933624,3.394508,1.945910,12.700787,3.394508,23.72,6,0,31.816667,32.35,7.290930,10.583333,11.75,28.924048,8.526662,1339,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,75_149_2,28.8,11.8,14,75_2_14,149_2_14,35.65,8.30,17380.352645,2,28.865348,8.671032,-6.168293,106.904214,-6.145721,106.956701,2026-01-01 00:14:18,413997.90
7,2026-01-01,RIDE-000008,02:43:46,CNR4510033,No Driver Found,Offline,CID3289424,eBike,Cideng,Johar Baru,8.3,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Found Alternative,Cancelled,Customer Unreachable,1.0,Customer Issue,2026-01-01 00:07:00,2,0,14,54,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.500000,0.866025,0.0,1.0,1,29.026393,-0.2,4.400,0,0,0.0,1339,7,167.375000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.042857,26.50,4.772091,8.400000,7.40,28.924048,8.526662,1339,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,14_54_2,28.8,8.3,43,14_2_43,54_2_43,28.80,12.90,17380.352645,2,28.865348,8.671032,-6.173681,106.809282,-6.183125,106.855332,2026-01-01 00:19:54,413999.63
8,2026-01-01,RIDE-000009,02:56:49,CNR9519641,Cancelled by Driver,Online,CID1177393,Motorcycle,Gondangdia,Pinangsia,7.7,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Changed Mind,Cancelled,No Reason Provided,1.0,No Reason Provided,2026-01-01 00:08:00,2,0,32,133,3,4.312727,3.207613,562.6384,4.870318,0,0,1,0.500000,0.866025,0.0,1.0,1,29.026393,-0.2,4.400,0,0,0.0,1339,6,191.285714,6,12.933624,3.394508,1.945910,12.700787,3.394508,23.72,6,0,30.616667,28.80,6.178160,10.983333,11.05,28.924048,8.526662,1339,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,32_133_2,28.8,7.7,56,32_2_56,133_2_56,20.23,9.50,17380.352645,2,28.865348,8.671032,-6.185911,106.832566,-6.135585,106.814641,2026-01-01 00:17:30,413999.61
9,2026-01-01,RIDE-000010,02:59:14,CNR4588428,No Driver Found,Offline,CID3087143,Auto,Cipedak,Kelapa Gading Barat,8.3,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,No Reason Provided,Cancelled,Traffic Issue,0.0,Route Problem,2026-01-01 00:09:00,2,0,21,79,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.500000,0.866025,0.0,1.0,1,29.026393,-0.2,4.400,0,0,0.0,1339,4,267.800000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,27.750000,26.95,3.823175,8.675000,9.60,28.924048,8.526662,1339,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,21_79_2,28.8,8.3,59,21_2_59,79_2_59,20.55,2.10,17380.352645,2,28.865348,8.671032,-6.351826,106.801629,-6.155602,106.895171,2026-01-01 00:11:06,413999.68

In [26]:
df_clean[['Booking Value', 'estimated_fare']].sample(20)

        Booking Value  estimated_fare
105286       414000.0       413998.98
80128        614000.0       553611.32
98798        270000.0       213190.51
97300        226000.0       207730.14
87363          1393.0        24575.22
26802           811.0        26794.40
50440        312000.0       234010.33
124601          915.0        30371.18
61170        374000.0       370287.37
11335          1535.0         9818.74
69242        248000.0       218794.36
149666       414000.0       413999.93
83397           978.0         9533.88
29528        447000.0       528490.19
104186       375000.0       369985.96
85634         56000.0        37391.89
147948       566000.0       538498.92
32198           848.0        26770.27
1065         446000.0       524845.01
27552           823.0        26238.62

In [27]:
df_clean.to_parquet('taxi_trip_engineering_2.parquet', index=False)