In [11]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## Import database

In [12]:
pd.set_option('display.max_columns', None)
df = pd.read_parquet('taxi_trip_engineering.parquet')
df

,Date,user_id,Time,Booking ID,Booking Status,Driver Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon,completed_at
0,2026-01-01,RIDE-000001,00:19:34,CNR4352144,Completed,Online,CID8362794,Motorcycle,Pasar Baru,Cilandak Timur,10.8,38.9,99000.0,37.98,4.8,4.8,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation,2026-01-01 00:00:00,0,0,110,18,4,4.312727,3.663049,1442.4804,6.162792,0,0,1,0.000000,1.000000,0.0,1.0,1,29.026393,0.00,4.625,0,0,4.8,1373,5,228.833333,5,11.502885,3.686376,1.791759,12.700787,3.394508,37.98,5,0,30.820000,31.20,9.496684,9.620000,10.80,29.024763,8.400510,1373,28.940847,8.432545,3,30.060481,8.487883,7.010743,9.6,23.04,4.8,4.8,4,29.983461,8.483689,110_18_0,38.9,10.8,19,110_0_19,18_0_19,18.90,11.55,2599.789916,0,29.126926,8.283577,-6.164901,106.833467,-6.289466,106.812477,2026-01-01 00:11:33
1,2026-01-01,RIDE-000002,01:35:18,CNR9147645,Completed,Online,CID8300238,Car,Kali Anyar,Rawamangun,8.5,15.1,114000.0,39.29,4.2,4.1,Uber Wallet,No Cancellation,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,No Reason Provided,2026-01-01 00:01:00,1,0,47,147,3,4.312727,3.696103,1543.7041,6.268174,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,0.10,4.150,0,1,4.2,1360,2,453.333333,2,11.643962,2.778819,1.098612,12.700787,3.394508,39.29,2,0,18.300000,18.30,4.525483,7.000000,7.00,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.105852,8.3,17.22,4.1,4.2,3,28.674842,8.418815,47_147_1,15.1,8.5,35,47_1_35,147_1_35,27.00,3.40,2894.135567,1,29.069894,8.250120,-7.550534,110.819452,-6.195928,106.884725,2026-01-01 00:04:24
2,2026-01-01,RIDE-000003,01:37:50,CNR1009222,Cancelled by Driver,Online,CID2030746,Go Sedan,Serdang,Pengadegan,7.4,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Traffic Issue,0.0,App Error,2026-01-01 00:02:00,1,0,147,125,1,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,4.3,1360,4,272.000000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,28.750000,28.80,0.100000,10.900000,9.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,147_125_1,28.8,7.4,37,147_1_37,125_1_37,20.10,8.60,17380.352645,2,28.865348,8.671032,3.034065,101.705568,-6.248914,106.854349,2026-01-01 00:10:36
3,2026-01-01,RIDE-000004,01:48:03,CNR2740479,Cancelled by Driver,Online,CID3231181,Auto,Tanah Tinggi,Kampung Rawa,5.6,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,Personal Issue,0.0,No Reason Provided,2026-01-01 00:03:00,1,0,160,61,2,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,4.3,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.914286,25.90,3.223057,6.571429,5.60,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,160_61_1,28.8,5.6,48,160_1_48,61_1_48,28.40,5.80,17380.352645,2,28.865348,8.671032,57.506636,-5.003837,-6.179512,106.855659,2026-01-01 00:08:48
4,2026-01-01,RIDE-000005,01:49:56,CNR7650148,Cancelled by Driver,Online,CID3381661,Go Sedan,Jati,Batu Ceper,6.2,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Wrong Pickup Location,Cancelled,Wrong Location,1.0,Route Problem,2026-01-01 00:04:00,1,0,40,2,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,0.0,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,23.542857,20.60,6.484303,5.514286,6.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,40_2_1,28.8,6.2,49,40_1_49,2_1_49,31.57,6.60,17380.352645,2,28.865348,8.671032,-7.689434,-39.006074,-6.172027,106.665287,2026-01-01 00:10:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2026-04-15,RIDE-149996,22:58:00,CNR9030698,Completed,Online,CID6939658,Motorcycle,Setu,Kembangan Utara,6.9,35.8,440000.0,12.85,4.4,4.8,UPI,Cancelled,Booked by Mistake,Cancelled,Wrong Location,0.0,App Error,2026-04-15 03:55:00,22,0,148,84,2,0.558696,2.628285,165.1225,3.584690,0,0,1,-0.500000,0.866025,0.0,1.0,1,25.260000,-0.40,4.600,0,0,0.0,5441,6,777.285714,6,12.994532,3.605498,1.945910,12.742693,3.268047,12.85,6,0,27.016667,26.15,6.237120,8.683333,7.95,29.112571,8.432659,5441,28.940847,8.432545,1,28.152500,8.043096,4.260973,9.2,21.12,4.4,4.8,4,29.983461,8.483689,148_84_22,35.8,6.9,58,148_22_58,84_22_58,28.80,7.55,33976.833977,3,29.283535,8.333253,-6.341971,106.664700,-6.173267,106.742726,2026-04-15 04:02:33
149996,2026-04-15,RIDE-149997,23:03:14,CNR1507833,Completed,Online,CID9905090,eBike,Jatinegara,Grogol Selatan,7.9,33.6,279000.0,39.36,3.8,4.3,UPI,No Cancellation,Changed Mind,No Cancellation,Vehicle Breakdown,0.0,No Reason Provided,2026-04-15 03:56:00,23,0,41,43,0,1.640000,3.697839,1549.2096,6.273755,0,0,1,-0.258819,0.965926,0.0,1.0,1,25.633333,-0.50,4.050,1,0,3.8,2762,4,552.400000,4,12.538971,3.543854,1.609438,12.331425,3.282164,39.36,4,0,27.625000,27.30,10.463389,7.750000,8.60,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,7.110858,8.1,16.34,3.8,4.3,3,28.674842,8.418815,41_43_23,33.6,7.9,3,41_23_3,43_23_3,15.20,6.30,7070.451090,1,29.069894,8.250120,-6.214925,106.870339,-6.230900,106.780309,2026-04-15 04:02:18
149997,2026-04-15,RIDE-149998,23:17:05,CNR2265113,Completed,Online,CID4170406,Car,Kebon Melati,Galur,9.9,39.9,1855.0,38.91,4.3,4.6,UPI,Cancelled,Changed Mind,Cancelled,Vehicle Breakdown,1.0,Ride Cancelled Midway,2026-04-15 03:57:00,23,0,69,36,4,1.621250,3.686627,1513.9881,6.237788,0,0,1,-0.258819,0.965926,0.0,1.0,1,27.000000,-0.30,4.450,0,0,0.0,2762,5,460.333333,5,7.526179,3.711130,1.791759,13.003582,3.332205,38.91,5,0,29.580000,28.80,8.277802,8.020000,9.90,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,7.078542,8.9,19.78,4.3,4.6,3,28.674842,8.418815,69_36_23,39.9,9.9,17,69_23_17,36_23_17,41.10,4.70,47.551910,0,29.126926,8.283577,-6.197487,106.816546,-7.950719,110.202904,2026-04-15 04:01:42
149998,2026-04-15,RIDE-149999,23:21:12,CNR4066733,Completed,Online,CID8938559,Uber XL,Utan Panjang,Pinang Ranti,2.6,26.7,520000.0,36.37,5.0,4.3,Uber Wallet,Cancelled,Changed Mind,Cancelled,Wrong Location,0.0,Route Problem,2026-04-15 03:58:00,23,0,174,132,1,1.515417,3.620868,1322.7769,6.030755,0,0,1,-0.258819,0.965926,0.0,1.0,1,25.833333,0.45,4.625,0,0,0.0,2762,4,552.400000,4,13.161586,3.321432,1.609438,12.861867,3.289645,36.37,4,0,26.050000,26.30,2.487971,6.675000,6.65,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,6.889998,9.3,21.50,4.3,5.0,4,29.983461,8.483689,174_132_23,26.7,2.6,21,174_23_21,132_23_21,27.30,9.20,14258.294489,3,29.283535,8.333253,-6.164872,106.854815,-6.288428,106.883331,2026-04-15 04:07:12
149999,2026-04-15,RIDE-150000,23:36:11,CNR6915581,Incomplete,Offline,CID5185745,Auto,Mampang Prapatan,Tegal Parang,3.5,11.9,571000.0,2.67,4.3,4.5,UPI,Cancelled,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,Route Problem,2026-04-15 03:59:00,23,0,94,168,1,0.111250,1.300192,7.1289,1.634013,0,0,1,-0.258819,0.965926,0.0,1.0,1,29.666667,-0.20,4.400,0,0,4.3,2762,10,251.090909,10,13.255146,2.557227,2.397895,12.865608,3.423176,2.67,10,0,27.890000,28.80,6.833813,8.140000,8.35,28.868356,8.447502,2762,28.940847,8.432545,0,27.916399,7.952362,1.482556,8.8,19.35,4.3,4.5,3,28.674842,8.418815,94_168_23,11.9,3.5,36,94_23_36,168_23_36,31.05,17.10,206137.184116,3,29.283535,8.333253,-6.250894,106.823022,-6.248909,106.829606,2026-04-15 04:16:06

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 97 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   user_id                            150000 non-null  object
 2   Time                               150000 non-null  object
 3   Booking ID                         150000 non-null  object
 4   Booking Status                     150000 non-null  object
 5   Driver Status                      150000 non-null  object
 6   Customer ID                        150000 non-null  object
 7   Vehicle Type                       150000 non-null  object
 8   Pickup Location                    150000 non-null  object
 9   Drop Location                      150000 non-null  object
 10  Avg VTAT                           150000 non-null  float64
 11  Avg CTAT                           150000 non-null  float64
 12  Booking Value                      150000 non-null  float64
 13  Ride Distance                      150000 non-null  float64
 14  Driver Ratings                     150000 non-null  float64
 15  Customer Rating                    150000 non-null  float64
 16  Payment Method                     150000 non-null  object
 17  Cancelled Rides by Customer        150000 non-null  object
 18  Reason for cancelling by Customer  150000 non-null  object
 19  Cancelled Rides by Driver          150000 non-null  object
 20  Driver Cancellation Reason         150000 non-null  object
 21  Incomplete Rides                   150000 non-null  float64
 22  Incomplete Rides Reason            150000 non-null  object
 23  Datetime                           150000 non-null  datetime64[ns]
 24  hour                               150000 non-null  int32
 25  day_of_week                        150000 non-null  int32
 26  Pickup Encoded                     150000 non-null  int64
 27  Drop Encoded                       150000 non-null  int64
 28  route_cluster                      150000 non-null  int32
 29  distance_per_hour                  150000 non-null  float64
 30  log_distance                       150000 non-null  float64
 31  distance_squared                   150000 non-null  float64
 32  distance_sqrt                      150000 non-null  float64
 33  is_peak_hour                       150000 non-null  int64
 34  is_weekend                         150000 non-null  int64
 35  is_night                           150000 non-null  int64
 36  hour_sin                           150000 non-null  float64
 37  hour_cos                           150000 non-null  float64
 38  day_sin                            150000 non-null  float64
 39  day_cos                            150000 non-null  float64
 40  traffic_score                      150000 non-null  int64
 41  route_avg_ctat_safe                150000 non-null  float64
 42  rating_diff                        150000 non-null  float64
 43  avg_rating                         150000 non-null  float64
 44  low_driver_rating                  150000 non-null  int64
 45  low_customer_rating                150000 non-null  int64
 46  driver_score                       150000 non-null  float64
 47  hourly_demand                      150000 non-null  int64
 48  route_demand                       150000 non-null  int64
 49  demand_pressure                    150000 non-null  float64
 50  route_count                        150000 non-null  int64
 51  log_price                          150000 non-null  float64
 52  log_ctat                           150000 non-null  float64
 53  log_route_count                    150000 non-null  float64
 54  log_route_price                    150000 non-null  float64
 55  log_route_ctat                     150000 non-null  float64
 56  time_distance_interaction          150000 non-null  float64
 57  route_complexity                   150000 non-null  int64
 58  peak_pressure                      150000 non-null  int64
 59  route_ctat_mean                    150000 non-null  float64
 60  route_ctat_median                  150000 non-null  float64
 61  route_ctat_std                     150000 non-null  float64
 62  route_vtat_mean                    150000 non-null  float64
 63  route_vtat_median                  150000 non-null  float64
 64  hour_avg_ctat                      150000 non-null  float64
 65  hour_avg_vtat                      150000 non-null  float64
 66  hour_demand                        150000 non-null  int64
 67  dow_avg_ctat                       150000 non-null  float64
 68  dow_avg_vtat                       150000 non-null  float64
 69  distance_bin                       150000 non-null  int64
 70  dist_bin_ctat                      150000 non-null  float64
 71  dist_bin_vtat                      150000 non-null  float64
 72  log_distance_v2                    150000 non-null  float64
 73  rating_sum                         150000 non-null  float64
 74  rating_mult                        150000 non-null  float64
 75  rating_min                         150000 non-null  float64
 76  rating_max                         150000 non-null  float64
 77  rating_bucket                      150000 non-null  int64
 78  rating_bucket_ctat                 150000 non-null  float64
 79  rating_bucket_vtat                 150000 non-null  float64
 80  route_hour_key                     150000 non-null  object
 81  route_hour_ctat                    150000 non-null  float64
 82  route_hour_vtat                    150000 non-null  float64
 83  minute                             150000 non-null  int32
 84  pickup_key                         150000 non-null  object
 85  drop_key                           150000 non-null  object
 86  estimated_pickup_time_minute       150000 non-null  float64
 87  estimated_drop_time_minute         150000 non-null  float64
 88  price_per_km                       150000 non-null  float64
 89  price_bucket                       150000 non-null  int64
 90  price_bucket_ctat                  150000 non-null  float64
 91  price_bucket_vtat                  150000 non-null  float64
 92  pickup_lat                         150000 non-null  float64
 93  pickup_lon                         150000 non-null  float64
 94  drop_lat                           150000 non-null  float64
 95  drop_lon                           150000 non-null  float64
 96  completed_at                       150000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(55), int32(4), int64(17), object(19)
memory usage: 108.7+ MB

In [14]:
df['Booking Value']

0          99000.0
1         114000.0
2         414000.0
3         414000.0
4         414000.0
            ...
149995    440000.0
149996    279000.0
149997      1855.0
149998    520000.0
149999    571000.0
Name: Booking Value, Length: 150000, dtype: float64

In [15]:
df["estimated_fare"] = df["Booking Value"]

In [16]:
df.isnull().sum()

Date              0
user_id           0
Time              0
Booking ID        0
Booking Status    0
                 ..
pickup_lon        0
drop_lat          0
drop_lon          0
completed_at      0
estimated_fare    0
Length: 98, dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 98 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   user_id                            150000 non-null  object
 2   Time                               150000 non-null  object
 3   Booking ID                         150000 non-null  object
 4   Booking Status                     150000 non-null  object
 5   Driver Status                      150000 non-null  object
 6   Customer ID                        150000 non-null  object
 7   Vehicle Type                       150000 non-null  object
 8   Pickup Location                    150000 non-null  object
 9   Drop Location                      150000 non-null  object
 10  Avg VTAT                           150000 non-null  float64
 11  Avg CTAT                           150000 non-null  float64
 12  Booking Value                      150000 non-null  float64
 13  Ride Distance                      150000 non-null  float64
 14  Driver Ratings                     150000 non-null  float64
 15  Customer Rating                    150000 non-null  float64
 16  Payment Method                     150000 non-null  object
 17  Cancelled Rides by Customer        150000 non-null  object
 18  Reason for cancelling by Customer  150000 non-null  object
 19  Cancelled Rides by Driver          150000 non-null  object
 20  Driver Cancellation Reason         150000 non-null  object
 21  Incomplete Rides                   150000 non-null  float64
 22  Incomplete Rides Reason            150000 non-null  object
 23  Datetime                           150000 non-null  datetime64[ns]
 24  hour                               150000 non-null  int32
 25  day_of_week                        150000 non-null  int32
 26  Pickup Encoded                     150000 non-null  int64
 27  Drop Encoded                       150000 non-null  int64
 28  route_cluster                      150000 non-null  int32
 29  distance_per_hour                  150000 non-null  float64
 30  log_distance                       150000 non-null  float64
 31  distance_squared                   150000 non-null  float64
 32  distance_sqrt                      150000 non-null  float64
 33  is_peak_hour                       150000 non-null  int64
 34  is_weekend                         150000 non-null  int64
 35  is_night                           150000 non-null  int64
 36  hour_sin                           150000 non-null  float64
 37  hour_cos                           150000 non-null  float64
 38  day_sin                            150000 non-null  float64
 39  day_cos                            150000 non-null  float64
 40  traffic_score                      150000 non-null  int64
 41  route_avg_ctat_safe                150000 non-null  float64
 42  rating_diff                        150000 non-null  float64
 43  avg_rating                         150000 non-null  float64
 44  low_driver_rating                  150000 non-null  int64
 45  low_customer_rating                150000 non-null  int64
 46  driver_score                       150000 non-null  float64
 47  hourly_demand                      150000 non-null  int64
 48  route_demand                       150000 non-null  int64
 49  demand_pressure                    150000 non-null  float64
 50  route_count                        150000 non-null  int64
 51  log_price                          150000 non-null  float64
 52  log_ctat                           150000 non-null  float64
 53  log_route_count                    150000 non-null  float64
 54  log_route_price                    150000 non-null  float64
 55  log_route_ctat                     150000 non-null  float64
 56  time_distance_interaction          150000 non-null  float64
 57  route_complexity                   150000 non-null  int64
 58  peak_pressure                      150000 non-null  int64
 59  route_ctat_mean                    150000 non-null  float64
 60  route_ctat_median                  150000 non-null  float64
 61  route_ctat_std                     150000 non-null  float64
 62  route_vtat_mean                    150000 non-null  float64
 63  route_vtat_median                  150000 non-null  float64
 64  hour_avg_ctat                      150000 non-null  float64
 65  hour_avg_vtat                      150000 non-null  float64
 66  hour_demand                        150000 non-null  int64
 67  dow_avg_ctat                       150000 non-null  float64
 68  dow_avg_vtat                       150000 non-null  float64
 69  distance_bin                       150000 non-null  int64
 70  dist_bin_ctat                      150000 non-null  float64
 71  dist_bin_vtat                      150000 non-null  float64
 72  log_distance_v2                    150000 non-null  float64
 73  rating_sum                         150000 non-null  float64
 74  rating_mult                        150000 non-null  float64
 75  rating_min                         150000 non-null  float64
 76  rating_max                         150000 non-null  float64
 77  rating_bucket                      150000 non-null  int64
 78  rating_bucket_ctat                 150000 non-null  float64
 79  rating_bucket_vtat                 150000 non-null  float64
 80  route_hour_key                     150000 non-null  object
 81  route_hour_ctat                    150000 non-null  float64
 82  route_hour_vtat                    150000 non-null  float64
 83  minute                             150000 non-null  int32
 84  pickup_key                         150000 non-null  object
 85  drop_key                           150000 non-null  object
 86  estimated_pickup_time_minute       150000 non-null  float64
 87  estimated_drop_time_minute         150000 non-null  float64
 88  price_per_km                       150000 non-null  float64
 89  price_bucket                       150000 non-null  int64
 90  price_bucket_ctat                  150000 non-null  float64
 91  price_bucket_vtat                  150000 non-null  float64
 92  pickup_lat                         150000 non-null  float64
 93  pickup_lon                         150000 non-null  float64
 94  drop_lat                           150000 non-null  float64
 95  drop_lon                           150000 non-null  float64
 96  completed_at                       150000 non-null  datetime64[ns]
 97  estimated_fare                     150000 non-null  float64
dtypes: datetime64[ns](2), float64(56), int32(4), int64(17), object(19)
memory usage: 109.9+ MB

## Split data into X and y & Feature Engineering & Data encoding

In [18]:
from sklearn.model_selection import train_test_split

df_clean = df.copy()

# Define leakage features
leakage_and_ids = [
    
     # Original IDs and targets
    'Booking Value', 'estimated_fare', 'log_price', 'price_per_km', 'log_route_price',
    'Booking ID', 'user_id', 'Customer ID', 'route_hour_key', 'pickup_key', 'drop_key', 
    'Date', 'Time', 'Datetime', 'completed_at',
    
    # Post-booking features that cause leakage
    'Booking Status', 'Driver Status', 'Cancelled Rides by Customer', 
    'Reason for cancelling by Customer', 'Cancelled Rides by Driver', 
    'Driver Cancellation Reason', 'Incomplete Rides', 'Incomplete Rides Reason'
]

# Split to features and target
X = df_clean.drop(columns=leakage_and_ids)
y = df_clean["estimated_fare"]


# Label encoding for categorical features
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in X.columns:
    if X[col].dtype == 'object':
        X[col] = le.fit_transform(X[col])

# Show data after encoding
X.head()

# Split to train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (120000, 75)
X_test shape: (30000, 75)

In [19]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 75 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Vehicle Type                  150000 non-null  int64
 1   Pickup Location               150000 non-null  int64
 2   Drop Location                 150000 non-null  int64
 3   Avg VTAT                      150000 non-null  float64
 4   Avg CTAT                      150000 non-null  float64
 5   Ride Distance                 150000 non-null  float64
 6   Driver Ratings                150000 non-null  float64
 7   Customer Rating               150000 non-null  float64
 8   Payment Method                150000 non-null  int64
 9   hour                          150000 non-null  int32
 10  day_of_week                   150000 non-null  int32
 11  Pickup Encoded                150000 non-null  int64
 12  Drop Encoded                  150000 non-null  int64
 13  route_cluster                 150000 non-null  int32
 14  distance_per_hour             150000 non-null  float64
 15  log_distance                  150000 non-null  float64
 16  distance_squared              150000 non-null  float64
 17  distance_sqrt                 150000 non-null  float64
 18  is_peak_hour                  150000 non-null  int64
 19  is_weekend                    150000 non-null  int64
 20  is_night                      150000 non-null  int64
 21  hour_sin                      150000 non-null  float64
 22  hour_cos                      150000 non-null  float64
 23  day_sin                       150000 non-null  float64
 24  day_cos                       150000 non-null  float64
 25  traffic_score                 150000 non-null  int64
 26  route_avg_ctat_safe           150000 non-null  float64
 27  rating_diff                   150000 non-null  float64
 28  avg_rating                    150000 non-null  float64
 29  low_driver_rating             150000 non-null  int64
 30  low_customer_rating           150000 non-null  int64
 31  driver_score                  150000 non-null  float64
 32  hourly_demand                 150000 non-null  int64
 33  route_demand                  150000 non-null  int64
 34  demand_pressure               150000 non-null  float64
 35  route_count                   150000 non-null  int64
 36  log_ctat                      150000 non-null  float64
 37  log_route_count               150000 non-null  float64
 38  log_route_ctat                150000 non-null  float64
 39  time_distance_interaction     150000 non-null  float64
 40  route_complexity              150000 non-null  int64
 41  peak_pressure                 150000 non-null  int64
 42  route_ctat_mean               150000 non-null  float64
 43  route_ctat_median             150000 non-null  float64
 44  route_ctat_std                150000 non-null  float64
 45  route_vtat_mean               150000 non-null  float64
 46  route_vtat_median             150000 non-null  float64
 47  hour_avg_ctat                 150000 non-null  float64
 48  hour_avg_vtat                 150000 non-null  float64
 49  hour_demand                   150000 non-null  int64
 50  dow_avg_ctat                  150000 non-null  float64
 51  dow_avg_vtat                  150000 non-null  float64
 52  distance_bin                  150000 non-null  int64
 53  dist_bin_ctat                 150000 non-null  float64
 54  dist_bin_vtat                 150000 non-null  float64
 55  log_distance_v2               150000 non-null  float64
 56  rating_sum                    150000 non-null  float64
 57  rating_mult                   150000 non-null  float64
 58  rating_min                    150000 non-null  float64
 59  rating_max                    150000 non-null  float64
 60  rating_bucket                 150000 non-null  int64
 61  rating_bucket_ctat            150000 non-null  float64
 62  rating_bucket_vtat            150000 non-null  float64
 63  route_hour_ctat               150000 non-null  float64
 64  route_hour_vtat               150000 non-null  float64
 65  minute                        150000 non-null  int32
 66  estimated_pickup_time_minute  150000 non-null  float64
 67  estimated_drop_time_minute    150000 non-null  float64
 68  price_bucket                  150000 non-null  int64
 69  price_bucket_ctat             150000 non-null  float64
 70  price_bucket_vtat             150000 non-null  float64
 71  pickup_lat                    150000 non-null  float64
 72  pickup_lon                    150000 non-null  float64
 73  drop_lat                      150000 non-null  float64
 74  drop_lon                      150000 non-null  float64
dtypes: float64(50), int32(4), int64(21)
memory usage: 83.5 MB

In [ ]:
X_train.head(2)

,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Ride Distance,Driver Ratings,Customer Rating,Payment Method,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_ctat,log_route_count,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_ctat,route_hour_vtat,minute,estimated_pickup_time_minute,estimated_drop_time_minute,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon
104025,2,89,116,12.0,44.1,22.86,4.9,4.2,0,19,0,89,116,1,1.143000,3.172203,522.5796,4.781213,1,0,0,-9.659258e-01,0.258819,0.000000,1.000000,3,17.966667,0.45,4.550,0,0,0.0,11047,7,1380.875000,7,3.808882,2.079442,2.839078,68.58,21,7,32.528571,38.20,12.327708,7.628571,9.20,29.012085,8.428614,11047,28.940847,8.432545,2,29.119842,8.707975,5.649910,9.1,20.58,4.2,4.9,4,29.983461,8.483689,44.10,12.00,23,16.30,6.50,1,29.069894,8.250120,-6.301672,106.779691,-6.210382,106.841227
5415,0,71,156,6.1,28.8,23.72,4.3,4.5,2,8,6,71,156,3,2.635556,3.207613,562.6384,4.870318,1,1,0,8.660254e-01,-0.500000,-0.781831,0.623490,1,29.026393,-0.20,4.400,0,0,4.3,6861,4,1372.200000,4,3.394508,1.609438,3.394508,23.72,4,4,32.350000,28.85,7.033491,10.650000,11.45,29.180251,8.506850,6861,29.139191,8.448285,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,35.85,9.85,54,44.80,4.85,2,28.865348,8.671032,-6.185082,106.831105,-6.206499,106.754106
75612,1,161,7,8.9,38.1,42.43,4.3,4.9,3,17,1,161,7,2,2.357222,3.771150,1800.3049,6.513831,1,0,0,-9.659258e-01,-0.258819,0.781831,0.623490,3,21.566667,-0.60,4.600,0,0,4.3,11044,7,1380.500000,7,3.666122,2.079442,3.116474,127.29,21,7,27.285714,26.50,9.480406,10.157143,8.90,28.995210,8.451911,11044,28.998560,8.431050,4,30.088452,8.531129,7.323367,9.2,21.07,4.3,4.9,4,29.983461,8.483689,38.10,8.90,31,28.80,5.00,0,29.126926,8.283577,-6.146566,106.823303,-6.242552,106.858690
138169,2,39,95,9.2,32.3,26.16,4.3,3.2,0,21,6,39,95,3,1.189091,3.301745,684.3456,5.114685,0,1,0,-7.071068e-01,0.707107,-0.781831,0.623490,2,33.250000,0.45,4.025,0,1,4.3,8103,11,675.250000,11,3.505557,2.484907,3.533687,52.32,22,0,32.563636,31.10,5.191391,8.500000,9.20,29.006319,8.386326,8103,29.139191,8.448285,2,29.119842,8.707975,5.999504,7.5,13.76,3.2,4.3,2,29.974975,8.567014,30.55,10.15,46,29.25,8.55,3,29.283535,8.333253,-6.330101,106.822237,-6.292874,106.903087
87184,4,147,136,12.4,21.5,48.85,3.3,3.3,0,12,1,147,136,1,3.757692,3.909018,2386.3225,6.989278,0,0,0,1.224647e-16,-1.000000,0.781831,0.623490,2,22.933333,0.00,4.025,1,1,0.0,7006,6,1000.857143,6,3.113515,1.945910,3.175272,97.70,12,0,25.466667,28.55,8.072092,9.033333,9.00,29.176749,8.463389,7006,28.998560,8.431050,4,30.088452,8.531129,7.728613,6.6,10.89,3.3,3.3,1,30.149957,8.527658,25.15,10.35,2,33.10,13.10,2,28.865348,8.671032,3.034065,101.705568,-6.115031,106.787362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119879,1,109,141,19.0,28.8,23.72,4.3,4.5,2,11,4,109,141,1,1.976667,3.207613,562.6384,4.870318,0,0,0,2.588190e-01,-0.965926,-0.433884,-0.900969,2,26.825000,-0.20,4.400,0,0,4.3,8390,5,1398.333333,5,3.394508,1.791759,3.325935,47.44,10,0,27.220000,28.80,3.532987,12.740000,10.50,28.932658,8.467735,8390,29.077287,8.478628,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,28.80,19.00,28,28.80,9.75,2,28.865348,8.671032,-6.258085,106.842733,-6.273637,106.778950
103694,1,171,155,2.9,20.7,13.70,4.3,4.5,0,22,6,171,155,1,0.595652,2.687847,187.6900,3.701351,0,1,1,-5.000000e-01,0.866025,-0.781831,0.623490,2,34.750000,-0.20,4.400,0,0,0.0,5441,4,1088.200000,4,3.077312,1.609438,3.576550,27.40,8,0,29.750000,29.60,7.542104,6.850000,7.30,29.112571,8.432659,5441,29.139191,8.448285,1,28.152500,8.043096,4.406634,8.8,19.35,4.3,4.5,3,28.674842,8.418815,20.70,2.90,36,33.85,5.30,0,29.126926,8.283577,-6.183453,106.964860,-6.195084,106.801244
131932,1,73,60,14.2,43.6,19.28,4.7,4.3,1,23,5,73,60,4,0.803333,3.009635,371.7184,4.390900,0,1,1,-2.588190e-01,0.965926,-0.974928,-0.222521,2,28.975000,0.40,4.500,0,0,0.0,2762,9,276.200000,9,3.797734,2.302585,3.400364,38.56,18,0,30.600000,28.80,9.073313,7.166667,6.60,28.868356,8.447502,2762,29.066303,8.436306,1,28.152500,8.043096,5.221205,9.0,20.21,4.3,4.7,3,28.674842,8.418815,43.60,14.20,50,33.60,8.30,1,29.069894,8.250120,-6.239801,106.614435,-6.219356,106.863619
146867,2,108,52,5.5,30.6,25.64,4.6,4.2,3,8,0,108,52,4,2.848889,3.282414,657.4096,5.063596,1,0,0,8.660254e-01,-0.500000,0.000000,1.000000,3,24.366667,0.40,4.400,0,0,4.6,6861,7,857.625000,7,3.453157,2.079442,3.233436,76.92,21,7,25.257143,28.80,6.408811,7.985714,7.10,29.180251,8.506850,6861,28.940847,8.432545,2,29.119842,8.707975,5.946891,8.8,19.32,4.2,4.6,3,28.674842,8.418815,30.60,5.50,36,24.90,8.30,2,28.865348,8.671032,-6.207920,106.797232,-6.144590,106.803928
121958,2,72,170,17.5,28.8,23.72,4.3,4.5,2,12,2,72,170,3,1.824615,3.207613,562.6384,4.870318,0,0,0,1.224647e-16,-1.000000,0.974928,-0.222521,2,34.020000,-0.20,4.400,0,0,4.3,7006,6,1000.857143,6,3.394508,1.945910,3.555919,47.44,12,0,33.150000,29.85,6.077088,11.650000,12.55,29.176749,8.463389,7006,29.015911,8.453472,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,35.65,14.85,56,23.50,2.60,2,28.865348,8.671032,-6.153092,106.758600,-6.183453,106.964860

## Scaling Data

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train shape:", X_train_scaled.shape)
print("X_test shape:", X_test_scaled.shape)

X_train shape: (120000, 75)
X_test shape: (30000, 75)

## Machine learning models prediction - Supervised Learning
### **Machine learning prediction method is regression because the data is linear**

In [22]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error


# Define models
MODELS = {
    "Random Forest": RandomForestRegressor(random_state=42),
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42)
}

# Define params
PARAMS_GRID = {
    "Random Forest": {
        "n_estimators": [100, 200],
        "max_depth": [None, 10, 20],
        "min_samples_split": [2, 5],
        "min_samples_leaf": [1, 2]
    },
    "Linear Regression": {},
    "Decision Tree": {
        "max_depth": [None, 10, 20],
        "min_samples_split": [2, 5],
        "min_samples_leaf": [1, 2]
    }
}

# Train and evaluate each models
for model_name, model in MODELS.items():
    print(f"Training {model_name}...")
    params = PARAMS_GRID[model_name] # Define params for grid search
    if params:
        grid_search = GridSearchCV(model,
                                   params,
                                   cv=5,
                                   scoring='r2',
                                   n_jobs=-1,
                                   verbose=1)
        grid_search.fit(X_train_scaled, y_train)

        # Define y_pred and evaluate
        y_pred = grid_search.predict(X_test_scaled)
        mse = mean_squared_error(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)
        mae = mean_absolute_error(y_test, y_pred)
        mape = mean_absolute_percentage_error(y_test, y_pred)
        print("\nEvaluation Metrics:")
        print(f"  MSE: {mse}")
        print(f"  R2: {r2}")
        print(f"  MAE: {mae}")
        print(f"  MAPE: {mape}")

        # Get best model from grid search
        best_model = grid_search.best_estimator_
        print(f"Best params for {model_name}: {grid_search.best_params_}")

    else:
        raise NotImplementedError(f"Model {model_name} does not have defined params for grid search.")
    

    # Show feature importance for best model
    if model_name in ["Random Forest", "Decision Tree", "Linear Regression"]:
        feature_importance = best_model.feature_importances_ if model_name != "Linear Regression" else best_model.coef_
        feature_importance_df = pd.DataFrame({
            "Feature": X.columns,
            "Importance": feature_importance
        })
        feature_importance_df = feature_importance_df.sort_values(by="Importance", ascending=False)
        print(f"\nFeature importance for {model_name}:")
        print(feature_importance_df.head(10))

Training Random Forest...
Fitting 5 folds for each of 24 candidates, totalling 120 fits

KeyboardInterrupt:

## Show on target column value after predicion

In [ ]:
# Applicated machine learning prediction on Target