In [30]:
import pandas as pd

pd.set_option('display.max_columns', None)
df = pd.read_parquet('taxi_trip_engineering.parquet')
df

,Date,user_id,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon,completed_at
0,2024-01-01,RIDE-000001,00:19:34,CNR4352144,Completed,CID8362794,Motorcycle,Pasar Baru,Cilandak Timur,10.8,38.9,99000.0,37.98,4.8,4.8,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation,2026-01-01 00:00:00,0,0,110,18,4,4.312727,3.663049,1442.4804,6.162792,0,0,1,0.000000,1.000000,0.0,1.0,1,29.026393,0.00,4.625,0,0,4.8,1373,5,228.833333,5,11.502885,3.686376,1.791759,12.700787,3.394508,37.98,5,0,30.820000,31.20,9.496684,9.620000,10.80,29.024763,8.400510,1373,28.940847,8.432545,3,30.060481,8.487883,7.010743,9.6,23.04,4.8,4.8,4,29.983461,8.483689,110_18_0,38.9,10.8,19,110_0_19,18_0_19,18.90,11.55,2599.789916,0,29.126926,8.283577,-6.164901,106.833467,-6.289466,106.812477,2026-01-01 00:11:33
1,2024-01-01,RIDE-000002,01:35:18,CNR9147645,Completed,CID8300238,Car,Kali Anyar,Rawamangun,8.5,15.1,114000.0,39.29,4.2,4.1,Uber Wallet,No Cancellation,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,No Reason Provided,2026-01-01 00:01:00,1,0,47,147,3,4.312727,3.696103,1543.7041,6.268174,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,0.10,4.150,0,1,4.2,1360,2,453.333333,2,11.643962,2.778819,1.098612,12.700787,3.394508,39.29,2,0,18.300000,18.30,4.525483,7.000000,7.00,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.105852,8.3,17.22,4.1,4.2,3,28.674842,8.418815,47_147_1,15.1,8.5,35,47_1_35,147_1_35,27.00,3.40,2894.135567,1,29.069894,8.250120,-7.550534,110.819452,-6.195928,106.884725,2026-01-01 00:04:24
2,2024-01-01,RIDE-000003,01:37:50,CNR1009222,Cancelled by Driver,CID2030746,Go Sedan,Serdang,Pengadegan,7.4,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Traffic Issue,0.0,App Error,2026-01-01 00:02:00,1,0,147,125,1,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,4.3,1360,4,272.000000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,28.750000,28.80,0.100000,10.900000,9.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,147_125_1,28.8,7.4,37,147_1_37,125_1_37,20.10,8.60,17380.352645,2,28.865348,8.671032,3.034065,101.705568,-6.248914,106.854349,2026-01-01 00:10:36
3,2024-01-01,RIDE-000004,01:48:03,CNR2740479,Cancelled by Driver,CID3231181,Auto,Tanah Tinggi,Kampung Rawa,5.6,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,Personal Issue,0.0,No Reason Provided,2026-01-01 00:03:00,1,0,160,61,2,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,4.3,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.914286,25.90,3.223057,6.571429,5.60,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,160_61_1,28.8,5.6,48,160_1_48,61_1_48,28.40,5.80,17380.352645,2,28.865348,8.671032,57.506636,-5.003837,-6.179512,106.855659,2026-01-01 00:08:48
4,2024-01-01,RIDE-000005,01:49:56,CNR7650148,Cancelled by Driver,CID3381661,Go Sedan,Jati,Batu Ceper,6.2,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Wrong Pickup Location,Cancelled,Wrong Location,1.0,Route Problem,2026-01-01 00:04:00,1,0,40,2,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.20,4.400,0,0,0.0,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,23.542857,20.60,6.484303,5.514286,6.20,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,40_2_1,28.8,6.2,49,40_1_49,2_1_49,31.57,6.60,17380.352645,2,28.865348,8.671032,-7.689434,-39.006074,-6.172027,106.665287,2026-01-01 00:10:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-12-30,RIDE-149996,22:58:00,CNR9030698,Completed,CID6939658,Motorcycle,Setu,Kembangan Utara,6.9,35.8,440000.0,12.85,4.4,4.8,UPI,Cancelled,Booked by Mistake,Cancelled,Wrong Location,0.0,App Error,2026-04-15 03:55:00,22,0,148,84,2,0.558696,2.628285,165.1225,3.584690,0,0,1,-0.500000,0.866025,0.0,1.0,1,25.260000,-0.40,4.600,0,0,0.0,5441,6,777.285714,6,12.994532,3.605498,1.945910,12.742693,3.268047,12.85,6,0,27.016667,26.15,6.237120,8.683333,7.95,29.112571,8.432659,5441,28.940847,8.432545,1,28.152500,8.043096,4.260973,9.2,21.12,4.4,4.8,4,29.983461,8.483689,148_84_22,35.8,6.9,58,148_22_58,84_22_58,28.80,7.55,33976.833977,3,29.283535,8.333253,-6.341971,106.664700,-6.173267,106.742726,2026-04-15 04:02:33
149996,2024-12-30,RIDE-149997,23:03:14,CNR1507833,Completed,CID9905090,eBike,Jatinegara,Grogol Selatan,7.9,33.6,279000.0,39.36,3.8,4.3,UPI,No Cancellation,Changed Mind,No Cancellation,Vehicle Breakdown,0.0,No Reason Provided,2026-04-15 03:56:00,23,0,41,43,0,1.640000,3.697839,1549.2096,6.273755,0,0,1,-0.258819,0.965926,0.0,1.0,1,25.633333,-0.50,4.050,1,0,3.8,2762,4,552.400000,4,12.538971,3.543854,1.609438,12.331425,3.282164,39.36,4,0,27.625000,27.30,10.463389,7.750000,8.60,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,7.110858,8.1,16.34,3.8,4.3,3,28.674842,8.418815,41_43_23,33.6,7.9,3,41_23_3,43_23_3,15.20,6.30,7070.451090,1,29.069894,8.250120,-6.214925,106.870339,-6.230900,106.780309,2026-04-15 04:02:18
149997,2024-12-30,RIDE-149998,23:17:05,CNR2265113,Completed,CID4170406,Car,Kebon Melati,Galur,9.9,39.9,1855.0,38.91,4.3,4.6,UPI,Cancelled,Changed Mind,Cancelled,Vehicle Breakdown,1.0,Ride Cancelled Midway,2026-04-15 03:57:00,23,0,69,36,4,1.621250,3.686627,1513.9881,6.237788,0,0,1,-0.258819,0.965926,0.0,1.0,1,27.000000,-0.30,4.450,0,0,0.0,2762,5,460.333333,5,7.526179,3.711130,1.791759,13.003582,3.332205,38.91,5,0,29.580000,28.80,8.277802,8.020000,9.90,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,7.078542,8.9,19.78,4.3,4.6,3,28.674842,8.418815,69_36_23,39.9,9.9,17,69_23_17,36_23_17,41.10,4.70,47.551910,0,29.126926,8.283577,-6.197487,106.816546,-7.950719,110.202904,2026-04-15 04:01:42
149998,2024-12-30,RIDE-149999,23:21:12,CNR4066733,Completed,CID8938559,Uber XL,Utan Panjang,Pinang Ranti,2.6,26.7,520000.0,36.37,5.0,4.3,Uber Wallet,Cancelled,Changed Mind,Cancelled,Wrong Location,0.0,Route Problem,2026-04-15 03:58:00,23,0,174,132,1,1.515417,3.620868,1322.7769,6.030755,0,0,1,-0.258819,0.965926,0.0,1.0,1,25.833333,0.45,4.625,0,0,0.0,2762,4,552.400000,4,13.161586,3.321432,1.609438,12.861867,3.289645,36.37,4,0,26.050000,26.30,2.487971,6.675000,6.65,28.868356,8.447502,2762,28.940847,8.432545,3,30.060481,8.487883,6.889998,9.3,21.50,4.3,5.0,4,29.983461,8.483689,174_132_23,26.7,2.6,21,174_23_21,132_23_21,27.30,9.20,14258.294489,3,29.283535,8.333253,-6.164872,106.854815,-6.288428,106.883331,2026-04-15 04:07:12
149999,2024-12-30,RIDE-150000,23:36:11,CNR6915581,Incomplete,CID5185745,Auto,Mampang Prapatan,Tegal Parang,3.5,11.9,571000.0,2.67,4.3,4.5,UPI,Cancelled,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,Route Problem,2026-04-15 03:59:00,23,0,94,168,1,0.111250,1.300192,7.1289,1.634013,0,0,1,-0.258819,0.965926,0.0,1.0,1,29.666667,-0.20,4.400,0,0,4.3,2762,10,251.090909,10,13.255146,2.557227,2.397895,12.865608,3.423176,2.67,10,0,27.890000,28.80,6.833813,8.140000,8.35,28.868356,8.447502,2762,28.940847,8.432545,0,27.916399,7.952362,1.482556,8.8,19.35,4.3,4.5,3,28.674842,8.418815,94_168_23,11.9,3.5,36,94_23_36,168_23_36,31.05,17.10,206137.184116,3,29.283535,8.333253,-6.250894,106.823022,-6.248909,106.829606,2026-04-15 04:16:06

In [32]:
pd.DataFrame(df['Booking ID'])

        Booking ID
0       CNR4352144
1       CNR9147645
2       CNR1009222
3       CNR2740479
4       CNR7650148
...            ...
149995  CNR9030698
149996  CNR1507833
149997  CNR2265113
149998  CNR4066733
149999  CNR6915581

[150000 rows x 1 columns]

In [26]:
# Delete "" from Booking ID and Customer ID columns
df['Booking ID'] = df['Booking ID'].str.replace('"', '')
df['Customer ID'] = df['Customer ID'].str.replace('"', '')

In [27]:
df.head()

,Date,user_id,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon,completed_at
0,2024-01-01,RIDE-000001,00:19:34,CNR4352144,Completed,CID8362794,Motorcycle,Pasar Baru,Cilandak Timur,10.8,38.9,99000.0,37.98,4.8,4.8,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation,2026-01-01 00:00:00,0,0,110,18,4,4.312727,3.663049,1442.4804,6.162792,0,0,1,0.000000,1.000000,0.0,1.0,1,29.026393,0.0,4.625,0,0,4.8,1373,5,228.833333,5,11.502885,3.686376,1.791759,12.700787,3.394508,37.98,5,0,30.820000,31.2,9.496684,9.620000,10.8,29.024763,8.400510,1373,28.940847,8.432545,3,30.060481,8.487883,7.010743,9.6,23.04,4.8,4.8,4,29.983461,8.483689,110_18_0,38.9,10.8,19,110_0_19,18_0_19,18.90,11.55,2599.789916,0,29.126926,8.283577,-6.164901,106.833467,-6.289466,106.812477,2026-01-01 00:11:33
1,2024-01-01,RIDE-000002,01:35:18,CNR9147645,Completed,CID8300238,Car,Kali Anyar,Rawamangun,8.5,15.1,114000.0,39.29,4.2,4.1,Uber Wallet,No Cancellation,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,No Reason Provided,2026-01-01 00:01:00,1,0,47,147,3,4.312727,3.696103,1543.7041,6.268174,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,0.1,4.150,0,1,4.2,1360,2,453.333333,2,11.643962,2.778819,1.098612,12.700787,3.394508,39.29,2,0,18.300000,18.3,4.525483,7.000000,7.0,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.105852,8.3,17.22,4.1,4.2,3,28.674842,8.418815,47_147_1,15.1,8.5,35,47_1_35,147_1_35,27.00,3.40,2894.135567,1,29.069894,8.250120,-7.550534,110.819452,-6.195928,106.884725,2026-01-01 00:04:24
2,2024-01-01,RIDE-000003,01:37:50,CNR1009222,Cancelled by Driver,CID2030746,Go Sedan,Serdang,Pengadegan,7.4,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Traffic Issue,0.0,App Error,2026-01-01 00:02:00,1,0,147,125,1,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,4.3,1360,4,272.000000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,28.750000,28.8,0.100000,10.900000,9.2,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,147_125_1,28.8,7.4,37,147_1_37,125_1_37,20.10,8.60,17380.352645,2,28.865348,8.671032,3.034065,101.705568,-6.248914,106.854349,2026-01-01 00:10:36
3,2024-01-01,RIDE-000004,01:48:03,CNR2740479,Cancelled by Driver,CID3231181,Auto,Tanah Tinggi,Kampung Rawa,5.6,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,Personal Issue,0.0,No Reason Provided,2026-01-01 00:03:00,1,0,160,61,2,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,4.3,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.914286,25.9,3.223057,6.571429,5.6,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,160_61_1,28.8,5.6,48,160_1_48,61_1_48,28.40,5.80,17380.352645,2,28.865348,8.671032,57.506636,-5.003837,-6.179512,106.855659,2026-01-01 00:08:48
4,2024-01-01,RIDE-000005,01:49:56,CNR7650148,Cancelled by Driver,CID3381661,Go Sedan,Jati,Batu Ceper,6.2,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Wrong Pickup Location,Cancelled,Wrong Location,1.0,Route Problem,2026-01-01 00:04:00,1,0,40,2,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,0.0,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,23.542857,20.6,6.484303,5.514286,6.2,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,40_2_1,28.8,6.2,49,40_1_49,2_1_49,31.57,6.60,17380.352645,2,28.865348,8.671032,-7.689434,-39.006074,-6.172027,106.665287,2026-01-01 00:10:36

In [29]:
df.to_parquet('taxi_trip_engineering.parquet', index=False)

In [28]:
df.columns.tolist()

['Date',
 'user_id',
 'Time',
 'Booking ID',
 'Booking Status',
 'Customer ID',
 'Vehicle Type',
 'Pickup Location',
 'Drop Location',
 'Avg VTAT',
 'Avg CTAT',
 'Booking Value',
 'Ride Distance',
 'Driver Ratings',
 'Customer Rating',
 'Payment Method',
 'Cancelled Rides by Customer',
 'Reason for cancelling by Customer',
 'Cancelled Rides by Driver',
 'Driver Cancellation Reason',
 'Incomplete Rides',
 'Incomplete Rides Reason',
 'Datetime',
 'hour',
 'day_of_week',
 'Pickup Encoded',
 'Drop Encoded',
 'route_cluster',
 'distance_per_hour',
 'log_distance',
 'distance_squared',
 'distance_sqrt',
 'is_peak_hour',
 'is_weekend',
 'is_night',
 'hour_sin',
 'hour_cos',
 'day_sin',
 'day_cos',
 'traffic_score',
 'route_avg_ctat_safe',
 'rating_diff',
 'avg_rating',
 'low_driver_rating',
 'low_customer_rating',
 'driver_score',
 'hourly_demand',
 'route_demand',
 'demand_pressure',
 'route_count',
 'log_price',
 'log_ctat',
 'log_route_count',
 'log_route_price',
 'log_route_ctat',
 'time_distance_interaction',
 'route_complexity',
 'peak_pressure',
 'route_ctat_mean',
 'route_ctat_median',
 'route_ctat_std',
 'route_vtat_mean',
 'route_vtat_median',
 'hour_avg_ctat',
 'hour_avg_vtat',
 'hour_demand',
 'dow_avg_ctat',
 'dow_avg_vtat',
 'distance_bin',
 'dist_bin_ctat',
 'dist_bin_vtat',
 'log_distance_v2',
 'rating_sum',
 'rating_mult',
 'rating_min',
 'rating_max',
 'rating_bucket',
 'rating_bucket_ctat',
 'rating_bucket_vtat',
 'route_hour_key',
 'route_hour_ctat',
 'route_hour_vtat',
 'minute',
 'pickup_key',
 'drop_key',
 'estimated_pickup_time_minute',
 'estimated_drop_time_minute',
 'price_per_km',
 'price_bucket',
 'price_bucket_ctat',
 'price_bucket_vtat',
 'pickup_lat',
 'pickup_lon',
 'drop_lat',
 'drop_lon',
 'completed_at']

In [24]:
df[['pickup_lat', 'pickup_lon', 'drop_lat', 'drop_lon']].head()

   pickup_lat  pickup_lon  drop_lat    drop_lon
0   -6.164901  106.833467 -6.289466  106.812477
1   -7.550534  110.819452 -6.195928  106.884725
2    3.034065  101.705568 -6.248914  106.854349
3   57.506636   -5.003837 -6.179512  106.855659
4   -7.689434  -39.006074 -6.172027  106.665287

In [22]:
df.columns.tolist()

['Date',
 'user_id',
 'Time',
 'Booking ID',
 'Booking Status',
 'Customer ID',
 'Vehicle Type',
 'Pickup Location',
 'Drop Location',
 'Avg VTAT',
 'Avg CTAT',
 'Booking Value',
 'Ride Distance',
 'Driver Ratings',
 'Customer Rating',
 'Payment Method',
 'Cancelled Rides by Customer',
 'Reason for cancelling by Customer',
 'Cancelled Rides by Driver',
 'Driver Cancellation Reason',
 'Incomplete Rides',
 'Incomplete Rides Reason',
 'Datetime',
 'hour',
 'day_of_week',
 'Pickup Encoded',
 'Drop Encoded',
 'route_cluster',
 'distance_per_hour',
 'log_distance',
 'distance_squared',
 'distance_sqrt',
 'is_peak_hour',
 'is_weekend',
 'is_night',
 'hour_sin',
 'hour_cos',
 'day_sin',
 'day_cos',
 'traffic_score',
 'route_avg_ctat_safe',
 'rating_diff',
 'avg_rating',
 'low_driver_rating',
 'low_customer_rating',
 'driver_score',
 'hourly_demand',
 'route_demand',
 'demand_pressure',
 'route_count',
 'log_price',
 'log_ctat',
 'log_route_count',
 'log_route_price',
 'log_route_ctat',
 'time_distance_interaction',
 'route_complexity',
 'peak_pressure',
 'route_ctat_mean',
 'route_ctat_median',
 'route_ctat_std',
 'route_vtat_mean',
 'route_vtat_median',
 'hour_avg_ctat',
 'hour_avg_vtat',
 'hour_demand',
 'dow_avg_ctat',
 'dow_avg_vtat',
 'distance_bin',
 'dist_bin_ctat',
 'dist_bin_vtat',
 'log_distance_v2',
 'rating_sum',
 'rating_mult',
 'rating_min',
 'rating_max',
 'rating_bucket',
 'rating_bucket_ctat',
 'rating_bucket_vtat',
 'route_hour_key',
 'route_hour_ctat',
 'route_hour_vtat',
 'minute',
 'pickup_key',
 'drop_key',
 'estimated_pickup_time_minute',
 'estimated_drop_time_minute',
 'price_per_km',
 'price_bucket',
 'price_bucket_ctat',
 'price_bucket_vtat',
 'pickup_lat',
 'pickup_lon',
 'drop_lat',
 'drop_lon',
 'completed_at']

## Get latitude and longitude column

In [8]:
from geopy.geocoders import Nominatim
import time

geolocator = Nominatim(user_agent="ride_app")

def get_lat_lon(location):
    if not location or pd.isna(location):
        return None, None
    
    try:
        loc = geolocator.geocode(location)
        time.sleep(1)  # To respect the usage policy of Nominatim
        return (loc.latitude, loc.longitude) if loc else (None, None)
    except:
        return None, None
    
# Usage
get_lat_lon("Jakarta, Indonesia")

(-6.1754049, 106.827168)

In [9]:
# Get a list of all Unique Locations
unique_locs = pd.concat([df['Pickup Location'], df['Drop Location']]).unique()
print(f"Total unique locations: {len(unique_locs)}")

# Geocode only the unique locations
cache = {}
for loc in unique_locs:
    cache[loc] = get_lat_lon(loc)

# Map the results back to original DataFrame
df['pickup_lat'], df['pickup_lon'] = zip(*df['Pickup Location'].map(cache))
df['drop_lat'], df['drop_lon'] = zip(*df['Drop Location'].map(cache))

Total unique locations: 230

In [10]:
df['Datetime'] = pd.date_range(start='2026-01-01', periods=len(df), freq='T')
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon
0,2024-01-01,00:19:34,"""CNR4352144""",Completed,"""CID8362794""",Motorcycle,Pasar Baru,Cilandak Timur,10.8,38.9,99000.0,37.98,4.8,4.8,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation,2026-01-01 00:00:00,0,0,110,18,4,4.312727,3.663049,1442.4804,6.162792,0,0,1,0.000000,1.000000,0.0,1.0,1,29.026393,0.0,4.625,0,0,4.8,1373,5,228.833333,5,11.502885,3.686376,1.791759,12.700787,3.394508,37.98,5,0,30.820000,31.2,9.496684,9.620000,10.8,29.024763,8.400510,1373,28.940847,8.432545,3,30.060481,8.487883,7.010743,9.6,23.04,4.8,4.8,4,29.983461,8.483689,110_18_0,38.9,10.8,19,110_0_19,18_0_19,18.90,11.55,2599.789916,0,29.126926,8.283577,-6.164901,106.833467,-6.289466,106.812477
1,2024-01-01,01:35:18,"""CNR9147645""",Completed,"""CID8300238""",Car,Kali Anyar,Rawamangun,8.5,15.1,114000.0,39.29,4.2,4.1,Uber Wallet,No Cancellation,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,No Reason Provided,2026-01-01 00:01:00,1,0,47,147,3,4.312727,3.696103,1543.7041,6.268174,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,0.1,4.150,0,1,4.2,1360,2,453.333333,2,11.643962,2.778819,1.098612,12.700787,3.394508,39.29,2,0,18.300000,18.3,4.525483,7.000000,7.0,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.105852,8.3,17.22,4.1,4.2,3,28.674842,8.418815,47_147_1,15.1,8.5,35,47_1_35,147_1_35,27.00,3.40,2894.135567,1,29.069894,8.250120,-7.550534,110.819452,-6.195928,106.884725
2,2024-01-01,01:37:50,"""CNR1009222""",Cancelled by Driver,"""CID2030746""",Go Sedan,Serdang,Pengadegan,7.4,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Traffic Issue,0.0,App Error,2026-01-01 00:02:00,1,0,147,125,1,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,4.3,1360,4,272.000000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,28.750000,28.8,0.100000,10.900000,9.2,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,147_125_1,28.8,7.4,37,147_1_37,125_1_37,20.10,8.60,17380.352645,2,28.865348,8.671032,3.034065,101.705568,-6.248914,106.854349
3,2024-01-01,01:48:03,"""CNR2740479""",Cancelled by Driver,"""CID3231181""",Auto,Tanah Tinggi,Kampung Rawa,5.6,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,Personal Issue,0.0,No Reason Provided,2026-01-01 00:03:00,1,0,160,61,2,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,4.3,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.914286,25.9,3.223057,6.571429,5.6,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,160_61_1,28.8,5.6,48,160_1_48,61_1_48,28.40,5.80,17380.352645,2,28.865348,8.671032,57.506636,-5.003837,-6.179512,106.855659
4,2024-01-01,01:49:56,"""CNR7650148""",Cancelled by Driver,"""CID3381661""",Go Sedan,Jati,Batu Ceper,6.2,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Wrong Pickup Location,Cancelled,Wrong Location,1.0,Route Problem,2026-01-01 00:04:00,1,0,40,2,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,0.0,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,23.542857,20.6,6.484303,5.514286,6.2,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,40_2_1,28.8,6.2,49,40_1_49,2_1_49,31.57,6.60,17380.352645,2,28.865348,8.671032,-7.689434,-39.006074,-6.172027,106.665287

In [11]:
df['completed_at'] = df['Datetime'] + pd.to_timedelta(df['estimated_drop_time_minute'], unit='m')
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon,completed_at
0,2024-01-01,00:19:34,"""CNR4352144""",Completed,"""CID8362794""",Motorcycle,Pasar Baru,Cilandak Timur,10.8,38.9,99000.0,37.98,4.8,4.8,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation,2026-01-01 00:00:00,0,0,110,18,4,4.312727,3.663049,1442.4804,6.162792,0,0,1,0.000000,1.000000,0.0,1.0,1,29.026393,0.0,4.625,0,0,4.8,1373,5,228.833333,5,11.502885,3.686376,1.791759,12.700787,3.394508,37.98,5,0,30.820000,31.2,9.496684,9.620000,10.8,29.024763,8.400510,1373,28.940847,8.432545,3,30.060481,8.487883,7.010743,9.6,23.04,4.8,4.8,4,29.983461,8.483689,110_18_0,38.9,10.8,19,110_0_19,18_0_19,18.90,11.55,2599.789916,0,29.126926,8.283577,-6.164901,106.833467,-6.289466,106.812477,2026-01-01 00:11:33
1,2024-01-01,01:35:18,"""CNR9147645""",Completed,"""CID8300238""",Car,Kali Anyar,Rawamangun,8.5,15.1,114000.0,39.29,4.2,4.1,Uber Wallet,No Cancellation,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,No Reason Provided,2026-01-01 00:01:00,1,0,47,147,3,4.312727,3.696103,1543.7041,6.268174,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,0.1,4.150,0,1,4.2,1360,2,453.333333,2,11.643962,2.778819,1.098612,12.700787,3.394508,39.29,2,0,18.300000,18.3,4.525483,7.000000,7.0,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.105852,8.3,17.22,4.1,4.2,3,28.674842,8.418815,47_147_1,15.1,8.5,35,47_1_35,147_1_35,27.00,3.40,2894.135567,1,29.069894,8.250120,-7.550534,110.819452,-6.195928,106.884725,2026-01-01 00:04:24
2,2024-01-01,01:37:50,"""CNR1009222""",Cancelled by Driver,"""CID2030746""",Go Sedan,Serdang,Pengadegan,7.4,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Traffic Issue,0.0,App Error,2026-01-01 00:02:00,1,0,147,125,1,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,4.3,1360,4,272.000000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,28.750000,28.8,0.100000,10.900000,9.2,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,147_125_1,28.8,7.4,37,147_1_37,125_1_37,20.10,8.60,17380.352645,2,28.865348,8.671032,3.034065,101.705568,-6.248914,106.854349,2026-01-01 00:10:36
3,2024-01-01,01:48:03,"""CNR2740479""",Cancelled by Driver,"""CID3231181""",Auto,Tanah Tinggi,Kampung Rawa,5.6,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,Personal Issue,0.0,No Reason Provided,2026-01-01 00:03:00,1,0,160,61,2,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,4.3,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.914286,25.9,3.223057,6.571429,5.6,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,160_61_1,28.8,5.6,48,160_1_48,61_1_48,28.40,5.80,17380.352645,2,28.865348,8.671032,57.506636,-5.003837,-6.179512,106.855659,2026-01-01 00:08:48
4,2024-01-01,01:49:56,"""CNR7650148""",Cancelled by Driver,"""CID3381661""",Go Sedan,Jati,Batu Ceper,6.2,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Wrong Pickup Location,Cancelled,Wrong Location,1.0,Route Problem,2026-01-01 00:04:00,1,0,40,2,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,0.0,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,23.542857,20.6,6.484303,5.514286,6.2,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,40_2_1,28.8,6.2,49,40_1_49,2_1_49,31.57,6.60,17380.352645,2,28.865348,8.671032,-7.689434,-39.006074,-6.172027,106.665287,2026-01-01 00:10:36

In [12]:
df[['Datetime', 'completed_at']].head(20)

              Datetime            completed_at
0  2026-01-01 00:00:00 2026-01-01 00:11:33.000
1  2026-01-01 00:01:00 2026-01-01 00:04:24.000
2  2026-01-01 00:02:00 2026-01-01 00:10:36.000
3  2026-01-01 00:03:00 2026-01-01 00:08:48.000
4  2026-01-01 00:04:00 2026-01-01 00:10:36.000
5  2026-01-01 00:05:00 2026-01-01 00:13:03.000
6  2026-01-01 00:06:00 2026-01-01 00:14:18.000
7  2026-01-01 00:07:00 2026-01-01 00:19:54.000
8  2026-01-01 00:08:00 2026-01-01 00:17:30.000
9  2026-01-01 00:09:00 2026-01-01 00:11:06.000
10 2026-01-01 00:10:00 2026-01-01 00:20:30.000
11 2026-01-01 00:11:00 2026-01-01 00:16:24.000
12 2026-01-01 00:12:00 2026-01-01 00:29:24.000
13 2026-01-01 00:13:00 2026-01-01 00:21:06.000
14 2026-01-01 00:14:00 2026-01-01 00:21:12.000
15 2026-01-01 00:15:00 2026-01-01 00:22:42.000
16 2026-01-01 00:16:00 2026-01-01 00:29:42.000
17 2026-01-01 00:17:00 2026-01-01 00:24:06.000
18 2026-01-01 00:18:00 2026-01-01 00:29:43.800
19 2026-01-01 00:19:00 2026-01-01 00:25:18.000

In [15]:
# Create user_id column
df['user_id'] = [f"RIDE-{i:06d}" for i in range(1, len(df) + 1)]
df.insert(1, 'user_id', df.pop('user_id'))
df.head()

,Date,user_id,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Datetime,hour,day_of_week,Pickup Encoded,Drop Encoded,route_cluster,distance_per_hour,log_distance,distance_squared,distance_sqrt,is_peak_hour,is_weekend,is_night,hour_sin,hour_cos,day_sin,day_cos,traffic_score,route_avg_ctat_safe,rating_diff,avg_rating,low_driver_rating,low_customer_rating,driver_score,hourly_demand,route_demand,demand_pressure,route_count,log_price,log_ctat,log_route_count,log_route_price,log_route_ctat,time_distance_interaction,route_complexity,peak_pressure,route_ctat_mean,route_ctat_median,route_ctat_std,route_vtat_mean,route_vtat_median,hour_avg_ctat,hour_avg_vtat,hour_demand,dow_avg_ctat,dow_avg_vtat,distance_bin,dist_bin_ctat,dist_bin_vtat,log_distance_v2,rating_sum,rating_mult,rating_min,rating_max,rating_bucket,rating_bucket_ctat,rating_bucket_vtat,route_hour_key,route_hour_ctat,route_hour_vtat,minute,pickup_key,drop_key,estimated_pickup_time_minute,estimated_drop_time_minute,price_per_km,price_bucket,price_bucket_ctat,price_bucket_vtat,pickup_lat,pickup_lon,drop_lat,drop_lon,completed_at
0,2024-01-01,RIDE-000001,00:19:34,"""CNR4352144""",Completed,"""CID8362794""",Motorcycle,Pasar Baru,Cilandak Timur,10.8,38.9,99000.0,37.98,4.8,4.8,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,0.0,No Cancellation,2026-01-01 00:00:00,0,0,110,18,4,4.312727,3.663049,1442.4804,6.162792,0,0,1,0.000000,1.000000,0.0,1.0,1,29.026393,0.0,4.625,0,0,4.8,1373,5,228.833333,5,11.502885,3.686376,1.791759,12.700787,3.394508,37.98,5,0,30.820000,31.2,9.496684,9.620000,10.8,29.024763,8.400510,1373,28.940847,8.432545,3,30.060481,8.487883,7.010743,9.6,23.04,4.8,4.8,4,29.983461,8.483689,110_18_0,38.9,10.8,19,110_0_19,18_0_19,18.90,11.55,2599.789916,0,29.126926,8.283577,-6.164901,106.833467,-6.289466,106.812477,2026-01-01 00:11:33
1,2024-01-01,RIDE-000002,01:35:18,"""CNR9147645""",Completed,"""CID8300238""",Car,Kali Anyar,Rawamangun,8.5,15.1,114000.0,39.29,4.2,4.1,Uber Wallet,No Cancellation,Wrong Pickup Location,No Cancellation,Customer Unreachable,1.0,No Reason Provided,2026-01-01 00:01:00,1,0,47,147,3,4.312727,3.696103,1543.7041,6.268174,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,0.1,4.150,0,1,4.2,1360,2,453.333333,2,11.643962,2.778819,1.098612,12.700787,3.394508,39.29,2,0,18.300000,18.3,4.525483,7.000000,7.0,28.935515,8.381618,1360,28.940847,8.432545,3,30.060481,8.487883,7.105852,8.3,17.22,4.1,4.2,3,28.674842,8.418815,47_147_1,15.1,8.5,35,47_1_35,147_1_35,27.00,3.40,2894.135567,1,29.069894,8.250120,-7.550534,110.819452,-6.195928,106.884725,2026-01-01 00:04:24
2,2024-01-01,RIDE-000003,01:37:50,"""CNR1009222""",Cancelled by Driver,"""CID2030746""",Go Sedan,Serdang,Pengadegan,7.4,28.8,414000.0,23.72,4.3,4.5,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Traffic Issue,0.0,App Error,2026-01-01 00:02:00,1,0,147,125,1,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,4.3,1360,4,272.000000,4,12.933624,3.394508,1.609438,12.700787,3.394508,23.72,4,0,28.750000,28.8,0.100000,10.900000,9.2,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,147_125_1,28.8,7.4,37,147_1_37,125_1_37,20.10,8.60,17380.352645,2,28.865348,8.671032,3.034065,101.705568,-6.248914,106.854349,2026-01-01 00:10:36
3,2024-01-01,RIDE-000004,01:48:03,"""CNR2740479""",Cancelled by Driver,"""CID3231181""",Auto,Tanah Tinggi,Kampung Rawa,5.6,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,Personal Issue,0.0,No Reason Provided,2026-01-01 00:03:00,1,0,160,61,2,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,4.3,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,25.914286,25.9,3.223057,6.571429,5.6,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,160_61_1,28.8,5.6,48,160_1_48,61_1_48,28.40,5.80,17380.352645,2,28.865348,8.671032,57.506636,-5.003837,-6.179512,106.855659,2026-01-01 00:08:48
4,2024-01-01,RIDE-000005,01:49:56,"""CNR7650148""",Cancelled by Driver,"""CID3381661""",Go Sedan,Jati,Batu Ceper,6.2,28.8,414000.0,23.72,4.3,4.5,Debit Card,Cancelled,Wrong Pickup Location,Cancelled,Wrong Location,1.0,Route Problem,2026-01-01 00:04:00,1,0,40,2,0,4.312727,3.207613,562.6384,4.870318,0,0,1,0.258819,0.965926,0.0,1.0,1,29.026393,-0.2,4.400,0,0,0.0,1360,7,170.000000,7,12.933624,3.394508,2.079442,12.700787,3.394508,23.72,7,0,23.542857,20.6,6.484303,5.514286,6.2,28.935515,8.381618,1360,28.940847,8.432545,2,29.119842,8.707975,5.744773,8.8,19.35,4.3,4.5,3,28.674842,8.418815,40_2_1,28.8,6.2,49,40_1_49,2_1_49,31.57,6.60,17380.352645,2,28.865348,8.671032,-7.689434,-39.006074,-6.172027,106.665287,2026-01-01 00:10:36

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 96 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  datetime64[ns]
 1   user_id                            150000 non-null  object
 2   Time                               150000 non-null  object
 3   Booking ID                         150000 non-null  object
 4   Booking Status                     150000 non-null  object
 5   Customer ID                        150000 non-null  object
 6   Vehicle Type                       150000 non-null  object
 7   Pickup Location                    150000 non-null  object
 8   Drop Location                      150000 non-null  object
 9   Avg VTAT                           150000 non-null  float64
 10  Avg CTAT                           150000 non-null  float64
 11  Booking Value                      150000 non-null  float64
 12  Ride Distance                      150000 non-null  float64
 13  Driver Ratings                     150000 non-null  float64
 14  Customer Rating                    150000 non-null  float64
 15  Payment Method                     150000 non-null  object
 16  Cancelled Rides by Customer        150000 non-null  object
 17  Reason for cancelling by Customer  150000 non-null  object
 18  Cancelled Rides by Driver          150000 non-null  object
 19  Driver Cancellation Reason         150000 non-null  object
 20  Incomplete Rides                   150000 non-null  float64
 21  Incomplete Rides Reason            150000 non-null  object
 22  Datetime                           150000 non-null  datetime64[ns]
 23  hour                               150000 non-null  int32
 24  day_of_week                        150000 non-null  int32
 25  Pickup Encoded                     150000 non-null  int64
 26  Drop Encoded                       150000 non-null  int64
 27  route_cluster                      150000 non-null  int32
 28  distance_per_hour                  150000 non-null  float64
 29  log_distance                       150000 non-null  float64
 30  distance_squared                   150000 non-null  float64
 31  distance_sqrt                      150000 non-null  float64
 32  is_peak_hour                       150000 non-null  int64
 33  is_weekend                         150000 non-null  int64
 34  is_night                           150000 non-null  int64
 35  hour_sin                           150000 non-null  float64
 36  hour_cos                           150000 non-null  float64
 37  day_sin                            150000 non-null  float64
 38  day_cos                            150000 non-null  float64
 39  traffic_score                      150000 non-null  int64
 40  route_avg_ctat_safe                150000 non-null  float64
 41  rating_diff                        150000 non-null  float64
 42  avg_rating                         150000 non-null  float64
 43  low_driver_rating                  150000 non-null  int64
 44  low_customer_rating                150000 non-null  int64
 45  driver_score                       150000 non-null  float64
 46  hourly_demand                      150000 non-null  int64
 47  route_demand                       150000 non-null  int64
 48  demand_pressure                    150000 non-null  float64
 49  route_count                        150000 non-null  int64
 50  log_price                          150000 non-null  float64
 51  log_ctat                           150000 non-null  float64
 52  log_route_count                    150000 non-null  float64
 53  log_route_price                    150000 non-null  float64
 54  log_route_ctat                     150000 non-null  float64
 55  time_distance_interaction          150000 non-null  float64
 56  route_complexity                   150000 non-null  int64
 57  peak_pressure                      150000 non-null  int64
 58  route_ctat_mean                    150000 non-null  float64
 59  route_ctat_median                  150000 non-null  float64
 60  route_ctat_std                     150000 non-null  float64
 61  route_vtat_mean                    150000 non-null  float64
 62  route_vtat_median                  150000 non-null  float64
 63  hour_avg_ctat                      150000 non-null  float64
 64  hour_avg_vtat                      150000 non-null  float64
 65  hour_demand                        150000 non-null  int64
 66  dow_avg_ctat                       150000 non-null  float64
 67  dow_avg_vtat                       150000 non-null  float64
 68  distance_bin                       150000 non-null  int64
 69  dist_bin_ctat                      150000 non-null  float64
 70  dist_bin_vtat                      150000 non-null  float64
 71  log_distance_v2                    150000 non-null  float64
 72  rating_sum                         150000 non-null  float64
 73  rating_mult                        150000 non-null  float64
 74  rating_min                         150000 non-null  float64
 75  rating_max                         150000 non-null  float64
 76  rating_bucket                      150000 non-null  int64
 77  rating_bucket_ctat                 150000 non-null  float64
 78  rating_bucket_vtat                 150000 non-null  float64
 79  route_hour_key                     150000 non-null  object
 80  route_hour_ctat                    150000 non-null  float64
 81  route_hour_vtat                    150000 non-null  float64
 82  minute                             150000 non-null  int32
 83  pickup_key                         150000 non-null  object
 84  drop_key                           150000 non-null  object
 85  estimated_pickup_time_minute       150000 non-null  float64
 86  estimated_drop_time_minute         150000 non-null  float64
 87  price_per_km                       150000 non-null  float64
 88  price_bucket                       150000 non-null  int64
 89  price_bucket_ctat                  150000 non-null  float64
 90  price_bucket_vtat                  150000 non-null  float64
 91  pickup_lat                         150000 non-null  float64
 92  pickup_lon                         150000 non-null  float64
 93  drop_lat                           150000 non-null  float64
 94  drop_lon                           150000 non-null  float64
 95  completed_at                       150000 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(55), int32(4), int64(17), object(17)
memory usage: 107.6+ MB

In [20]:
df.columns.to_list()

['Date',
 'user_id',
 'Time',
 'Booking ID',
 'Booking Status',
 'Customer ID',
 'Vehicle Type',
 'Pickup Location',
 'Drop Location',
 'Avg VTAT',
 'Avg CTAT',
 'Booking Value',
 'Ride Distance',
 'Driver Ratings',
 'Customer Rating',
 'Payment Method',
 'Cancelled Rides by Customer',
 'Reason for cancelling by Customer',
 'Cancelled Rides by Driver',
 'Driver Cancellation Reason',
 'Incomplete Rides',
 'Incomplete Rides Reason',
 'Datetime',
 'hour',
 'day_of_week',
 'Pickup Encoded',
 'Drop Encoded',
 'route_cluster',
 'distance_per_hour',
 'log_distance',
 'distance_squared',
 'distance_sqrt',
 'is_peak_hour',
 'is_weekend',
 'is_night',
 'hour_sin',
 'hour_cos',
 'day_sin',
 'day_cos',
 'traffic_score',
 'route_avg_ctat_safe',
 'rating_diff',
 'avg_rating',
 'low_driver_rating',
 'low_customer_rating',
 'driver_score',
 'hourly_demand',
 'route_demand',
 'demand_pressure',
 'route_count',
 'log_price',
 'log_ctat',
 'log_route_count',
 'log_route_price',
 'log_route_ctat',
 'time_distance_interaction',
 'route_complexity',
 'peak_pressure',
 'route_ctat_mean',
 'route_ctat_median',
 'route_ctat_std',
 'route_vtat_mean',
 'route_vtat_median',
 'hour_avg_ctat',
 'hour_avg_vtat',
 'hour_demand',
 'dow_avg_ctat',
 'dow_avg_vtat',
 'distance_bin',
 'dist_bin_ctat',
 'dist_bin_vtat',
 'log_distance_v2',
 'rating_sum',
 'rating_mult',
 'rating_min',
 'rating_max',
 'rating_bucket',
 'rating_bucket_ctat',
 'rating_bucket_vtat',
 'route_hour_key',
 'route_hour_ctat',
 'route_hour_vtat',
 'minute',
 'pickup_key',
 'drop_key',
 'estimated_pickup_time_minute',
 'estimated_drop_time_minute',
 'price_per_km',
 'price_bucket',
 'price_bucket_ctat',
 'price_bucket_vtat',
 'pickup_lat',
 'pickup_lon',
 'drop_lat',
 'drop_lon',
 'completed_at']

## Save data into parquet

In [16]:
df.to_parquet('taxi_trip_engineering.parquet', index=False)

In [17]:
df.isnull().sum()

Date              0
user_id           0
Time              0
Booking ID        0
Booking Status    0
                 ..
pickup_lat        0
pickup_lon        0
drop_lat          0
drop_lon          0
completed_at      0
Length: 96, dtype: int64

In [18]:
object_columns = df.select_dtypes(include='object')
object_columns

,user_id,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Payment Method,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides Reason,route_hour_key,pickup_key,drop_key
0,RIDE-000001,00:19:34,"""CNR4352144""",Completed,"""CID8362794""",Motorcycle,Pasar Baru,Cilandak Timur,Cash,No Cancellation,No Cancellation,No Cancellation,No Cancellation,No Cancellation,110_18_0,110_0_19,18_0_19
1,RIDE-000002,01:35:18,"""CNR9147645""",Completed,"""CID8300238""",Car,Kali Anyar,Rawamangun,Uber Wallet,No Cancellation,Wrong Pickup Location,No Cancellation,Customer Unreachable,No Reason Provided,47_147_1,47_1_35,147_1_35
2,RIDE-000003,01:37:50,"""CNR1009222""",Cancelled by Driver,"""CID2030746""",Go Sedan,Serdang,Pengadegan,Debit Card,No Cancellation,Booked by Mistake,No Cancellation,Traffic Issue,App Error,147_125_1,147_1_37,125_1_37
3,RIDE-000004,01:48:03,"""CNR2740479""",Cancelled by Driver,"""CID3231181""",Auto,Tanah Tinggi,Kampung Rawa,Debit Card,Cancelled,Driver Taking Too Long,No Cancellation,Personal Issue,No Reason Provided,160_61_1,160_1_48,61_1_48
4,RIDE-000005,01:49:56,"""CNR7650148""",Cancelled by Driver,"""CID3381661""",Go Sedan,Jati,Batu Ceper,Debit Card,Cancelled,Wrong Pickup Location,Cancelled,Wrong Location,Route Problem,40_2_1,40_1_49,2_1_49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,RIDE-149996,22:58:00,"""CNR9030698""",Completed,"""CID6939658""",Motorcycle,Setu,Kembangan Utara,UPI,Cancelled,Booked by Mistake,Cancelled,Wrong Location,App Error,148_84_22,148_22_58,84_22_58
149996,RIDE-149997,23:03:14,"""CNR1507833""",Completed,"""CID9905090""",eBike,Jatinegara,Grogol Selatan,UPI,No Cancellation,Changed Mind,No Cancellation,Vehicle Breakdown,No Reason Provided,41_43_23,41_23_3,43_23_3
149997,RIDE-149998,23:17:05,"""CNR2265113""",Completed,"""CID4170406""",Car,Kebon Melati,Galur,UPI,Cancelled,Changed Mind,Cancelled,Vehicle Breakdown,Ride Cancelled Midway,69_36_23,69_23_17,36_23_17
149998,RIDE-149999,23:21:12,"""CNR4066733""",Completed,"""CID8938559""",Uber XL,Utan Panjang,Pinang Ranti,Uber Wallet,Cancelled,Changed Mind,Cancelled,Wrong Location,Route Problem,174_132_23,174_23_21,132_23_21
149999,RIDE-150000,23:36:11,"""CNR6915581""",Incomplete,"""CID5185745""",Auto,Mampang Prapatan,Tegal Parang,UPI,Cancelled,Wrong Pickup Location,No Cancellation,Customer Unreachable,Route Problem,94_168_23,94_23_36,168_23_36